### ISSUE TITLE
Implement external link icon for nested NavItem

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#1032]
### Why?

We should separate external links visually.

### Design

- [Figma](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1625%3A41198&mode=dev)
- Looks the same as in the other places

### Acceptance criteria

- [x] Arrow icon should be visible next to the label

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/support-navitem--with-options)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

#### Reference implementations

OnyxNavItem, OnyxLink

**Comment by jannick-ux** [comment]
Please set the padding between the text and the arrow-icon to 0. We have it the same way in the link-component.

**Comment by MajaZarkova** [comment]
There is a bug ticket for that -> #1148
