### ISSUE TITLE
Implement OnyxSelect flyout opening direction and alignment

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1198]
### Open question

- Should we also support to manually set a fixed open direction?

### Why?

The flyout of the `OnyxSelect` should detect in which direction it should open (top or bottom), depending on in which direction more space is available.
It should also support to align left/right if not using the full parent width

### Design

[Figma](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=4462-57174&m=dev)

### Acceptance criteria

- [x] if more space is available above the select, its opened to the top
- [x] if more space is available below the select, its opened to the bottom
- [x] by default the flyout uses the full width of the select
- [x] the width can optionally be limited and aligned left/right

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary -> #1764 
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Storybook top open direction](https://storybook.onyx.schwarz/?path=/story/form-select--with-top-open-direction)
- [Storybook Right alignment](https://storybook.onyx.schwarz/?path=/story/form-select--with-right-alignment)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation Details

- [ViusalViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport)
- don't change the direction on scroll -> try out how it feels.
- prefer to solve the width things with CSS only

**Comment by larsrickert** [comment]
@MajaZarkova When using the select with search, the flyout width increases to more than the content width, is this intended?


![Image](https://github.com/user-attachments/assets/66c7f4c8-6b8b-4c98-ace3-4cb710f53756)
