### ISSUE TITLE
Concept Table focus outline, skeleton, empty & loading

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1225]
1. Define how the table looks when focused (is needed so the table can be scrolled with the keyboard)
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/38c759bb-de1f-4e9b-9980-2d9651ea257b)

2. Define how the table looks in skeleton mode

**Comment by jannick-ux** [comment]
https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=5129-26998&t=X6MwF6EN8gsHzc0G-4

Follow the definitions of the figma link.
Loading will not be part of it for now.
