### ISSUE TITLE
Onboard WaWi UI/UX colleagues

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#123]
The WaWi UI/UX development colleagues must be onboarded about onyx in a dedicated meeting.
Proposed agenda:
- How to work with Github
  - Creating and searching Github Issues
  - Seeing tickets and milestones in Github Projects
  - Fork & Pull Request workflow on Github
- Our project structure
  - our packages

**Comment by JoCa96** [comment]
would be superb if @larsrickert and/or @BoppLi could take over this task :) Great chance to get acquainted!

**Comment by larsrickert** [comment]
Could you provide a list of WaWi collegues? Or maybe you can schedule the meeting, I can take over the onboarding
