### ISSUE TITLE
Implement Table empty + focus outline

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1240]
### Depends on 

- #1225

### Why?

Provide missing features for OnyxTable.

### Design

[Figma table definitions](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=5129-26998&t=X6MwF6EN8gsHzc0G-4)

![image](https://github.com/SchwarzIT/onyx/assets/151019977/31e31b22-0009-4a00-a2ea-a54236ef8ee4)

### Out of scope

- #1421

### Acceptance criteria

- [x] offer empty state
- [x] implement focus style when accessing the table with tab

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Storybook Empty Table](https://storybook.onyx.schwarz/?path=/story/data-table--empty)
- [Storybook focused table](https://storybook.onyx.schwarz/?path=/story/data-table--default) -> access table with tab.
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

- Use the exisiting empty component
- prefer CSS implementation, e.g. with `&:has(tbody tr)` selector

**Comment by mj-hof** [comment]
@jannick-ux Open question
- Reconsider skeleton for simple table to be replace by a lading indicator style?

**Comment by jannick-ux** [comment]
loading indicator and skeleton state have two different purposes. Skeleton is for building up the component. Loading indicator is for processing an input. Thats the reason why we commited to skip the loading indicator for the simple table.
