### ISSUE TITLE
Fix table header sticky issue in page context

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1242]
In the following ticket it was defined:
- #840 
> The header sticks to the top of the scroll-area **when the page is scrolled, with the table on it**

During the initial implementation it once worked in the alpha test app.  
Now it does not work anymore:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/cf28d9e8-50d3-416d-973c-d4d075cfd568)

Reproduce bei starting the alpha test app and opening http://localhost:5173/. resize the height of the browser window a lot, then scroll down. the table header does not stick below the nav-bar as expected.

**Comment by larsrickert** [comment]
For me it does not make sense that the header sticks when the page is scrolled...it should only stick if the table height itself is limited.

If you want the whole table to be sticky, you need to set `position: sticky` on the table

**Comment by BoppLi** [comment]
> For me it does not make sense that the header sticks when the page is scrolled...it should only stick if the table height itself is limited.
> 
> If you want the whole table to be sticky, you need to set `position: sticky` on the table

see https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=4435-44042&m=dev for context, there is a valid usecase for this and setting position: sticky on the table did not fulfill the desired behavior, it's even considered best-practice e.g. for mobile according to Jannick's description.
the table-headers `sticky` will only be applied to the next-best scroll container, that's why I needed to disable our table scroll container with the new prop to achieve this behavior.

**Comment by BoppLi** [comment]
Discussion Decision: Table scrolling will be the default, @jannick-ux  could you mark it in figma? we can have a call if you want context about the technical background of this.
