### ISSUE TITLE
Align all onyx namings (Figma & Implementation)

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#1274]
### Depends on

- #883

### Why?

We want to align all namings in onyx between Figma and the dev implementation.

### Acceptance criteria

- [x] component names are aligned (if possible prefer the name of the implemented [aria pattern](https://www.w3.org/WAI/ARIA/apg/patterns/))
- [x] property names are aligned
- [x] component/property textual descriptions are aligned
- [x] token names are aligned and the [GitHub action](https://github.com/SchwarzIT/onyx/actions/workflows/import-figma.yml) is trigger to update them to the latest values
- [x] #1055

### Definition of Done

- [x] updated version + documentation is deployed
- [x] Storybook can show the feature

**Approval**

- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert

**Comment by larsrickert** [comment]
Open DEV points:

- OnyxSelect: support `description` for flyout
- OnyxSelectOption: remove `color` property
- OnyxIcon / OnyxAvatar: Discuss if naming should be tshirt sizes
- OnyxTable: find better name for `withVerticalBorder` property, maybe rename again to `grid` ?
- MiniSearch: Add magnifier icon when empty
- align with Jonathan about support components for flyouts (e.g. name of OnyxSelectOption)
