### ISSUE TITLE
Implement beta release changes

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#1275]
To-dos:
- [x] Release prep is not allowed to be merged before third of July.
- [x] All versions must have a change set with a major change, so that it has version 1.0.0-beta.X after the beta release.
- [x] Include the word "Changelog" on all Changelog vitepress page, so they can be found via the search
- [x] Rename "alpha" to "beta"
  - [x] Update release tag: `.changeset/pre.json`
  - [x] Docs: wherever it is named "we are in alpha", rename it to "beta"
  - [x] Config file for the release artifact: set beta instead of alpha for our NPM packages

**Comment by larsrickert** [comment]
Meeting scheduled for 20th June
