### ISSUE TITLE
Adjust drop shadow on flyout for darkmode

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1291]
On lightmode, a drop shadow is visible (example from [OnyxSelect](https://storybook.onyx.schwarz/?path=/docs/components-select--docs)):
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/752f3cca-640f-45e7-8817-e4f9d0593419)

In darkmode, this can't be seen
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/d7b1288a-aa81-42c9-a57f-85ddc865c944)

**Comment by larsrickert** [comment]
Thats intended by UX because shadows do not work in dark mode in general, see https://onyx.schwarz/tokens/shadows.html

**Comment by BoppLi** [comment]
after talking to jannick I created https://github.com/SchwarzIT/onyx/issues/1309
