### ISSUE TITLE
Implement OnyxStepper

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#1348]
### Open question

- @jannick-ux  Do we plan to create an additional component for entering very large numbers or numbers with many decimal places? If so, we don't need to implement the BigInt and custom decimal type for this ticket
- @jannick-ux Idea: Should we use monospace font?

### Why?

We want to support a stepper component that is optimised for entering numbers.

### Design

[Figma](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=5041-2580&t=zdXvmCyp6tpZ7T07-4)

### Acceptance criteria

- [x] design is implemented (and numbers are always centered)
- [x] supports positive, negative and decimal numbers
- [x] supports even and decimal steps
- [x] supports both dot and comma for entering decimal values
- [ ] can optionally put into "strip step" mode so that when manually entering values that do not fit the step size, a stepMismatch error is shown
- [ ] can optionally define a "precision" for the displayed value to always display the given number of decimals places, e.g. "3.00"
- [x] decrease/increase button is disabled when min/max value is reached
- [x] can be set to loading state
- the following native HTML properties are supported:
  - [x] autofocus
  - [x] autocomplete
- [x] error handling / error messages are supported for min, max and step property (see [this comment](https://github.com/SchwarzIT/onyx/issues/1273#issuecomment-2160150647))

### Out of scope

- [ ] can optionally put into "strip step" mode so that when manually entering values that do not fit the step size, a stepMismatch error is shown
- [ ] can optionally define a "precision" for the displayed value to always display the given number of decimals places, e.g. "3.00"
- [ ] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [ ] example usage added to `apps/alpha-test-app/src/views/FormDemo.vue`

### Definition of Done

- The following component requirements are implemented:
  - [x] `skeleton`
  - [x] `density`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary -> #1587 
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/docs/form-stepper--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @BoppLi 
### Implementation details

- implemented using the generic [FormElement](https://storybook.onyx.schwarz/?path=/docs/support-formelement--docs) support component
- Consider the advise: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#accessibility

### Reference implementations

- [Element plus](https://element-plus.org/en-US/component/input-number.html)

**Comment by JoCa96** [comment]
We must consider the following edge cases:
- Big numbers: We should add support for [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
- Decimal: We should support custom decimal type, as the primitive number can become inaccurate

**Comment by jannick-ux** [comment]
- I did not really think about splitting up the component for different usecases. If there is the technical necessity on it, it is fine for me. But in figma it still would be one single component, because there would not be a visual difference. 
- Supporting monospace should be possible but not the default.

**Comment by JoCa96** [comment]
The [spinbutton](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/) aria pattern applies to this component and needs to be applied.

**Comment by BoppLi** [comment]
@MajaZarkova could you move the marked lines before the 

![Image](https://github.com/user-attachments/assets/c7809596-5626-4691-a1c7-5c1a704b01f5)

because of the sass deprecation warning which was already solved elsewhere?

![Image](https://github.com/user-attachments/assets/8ea0acd5-6dce-460d-974b-455485e17eec)

Same with the other parts where the warning comes up when running pnpm start in sit-onyx

**Comment by MajaZarkova** [comment]
> The [spinbutton](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/) aria pattern applies to this component and needs to be applied.

Added as acceptance criteria in the follow up ticket -> #1587
