### ISSUE TITLE
Implement OnyxSelect API refactoring

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1397]
### Why?

We want to improve the DX for the majority of devs that use OnyxSelect.

### Acceptance criteria

- [x] Prio 1 of the ticket: finalize the concept. it's just a draft that is written below.

Changes inside of OnyxSelect
- [x] change modelValue property to only `TValue`/`TValue[]`
- [x] per default, resolve initial modelValues to find the labels in the given `options`
- [x] add new prop to overwrite the displayed labels: (to be defined whether  `string`/`string[]`)
- [x] add new prop to overwrite filter function, which defaults to our utility func `normalizedIncludes`. 
  - [x] defaults means, when the `useManagedState` says so.
  - [x] call filter function inside of OnyxSelect
  - [x] can be deactivated

### Definition of Done

- [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] follow-up tickets were created if necessary
  - #1649
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Select with modelValue "mango" (= just the value)](https://storybook.onyx.schwarz/?path=/story/form-select--default&args=open:!false;modelValue:mango)
- [Select with integrated search](https://storybook.onyx.schwarz/?path=/story/form-select--with-search)
- [x] approved by designer @mj-hof 
- [x] approved by dev @larsrickert 

#### Sync example

```vue
<script>
const modelValue = ref<string>("1");
const options = ref(Array(10).fill(null).map(n => ({value: `${n}`, label: `${n}`})));
</script>

<template>
<OnyxSelect v-model="modelValue" :options="options" />
</template>
```

#### Async example

```vue
<script>
const modelValue = ref<string>("2"); // has initial selection
const options = ref<SelectOptions<string>[]>([])
const load = async () => {
   await setTimeout(2000);
   options.value = Array(10).fill(null).map(n => ({value: `${n}`, label: `label ${n}`}))
}

onMounted(() => load());
</script>

<template>
<OnyxSelect v-model="modelValue" :options="options" :selectionLabel="`label ${modelValue}`"  /> <!-- ideally would show "label 2" from the beginning -->
</template>
```

#### Filtering/Pagination:
```vue
<script>
const modelValue = ref<string>("2"); // has initial selection
const options = ref<SelectOptions<string>[]>([])

const load = async (searchTerm: string) => {
   await setTimeout(2000);
   options.value = Array(10).fill(null).map(n => ({value: `${searchTerm} ${n}`, label: `${searchTerm} label ${n}`}))
}

onMounted(() => load(""));
</script>

<template>
<OnyxSelect v-model="modelValue" :options="options" :selectionLabel="`label ${modelValue}`" /> <!-- what to do when the selected option is not provided? -->
</template>
```

**Comment by jannick-ux** [comment]
@BoppLi The search needs to be active the moment you open the flyout. The user should not need to klick into the searchfield to activate ist. He should be able to just start typing.

**Comment by larsrickert** [comment]
- Do we need the `manualSearch` property? Couldn't we also say if the user binds the v-model:searchTerm, then its manual search? Is there any use case where the user would bind v-model:searchTerm but not filter manually?
- The flyout closes when pressing space, although it should be possible to search values with spaces
- Should we still mention our `normalizeIncludes` utility function for the manual search?
- Probably not related to this ticket, but why does the Select have a `showFocus` property? I though this is only used internally? Also it does not seem to have any effect

**Comment by BoppLi** [comment]
> [@BoppLi](https://github.com/BoppLi) The search needs to be active the moment you open the flyout. The user should not need to klick into the searchfield to activate ist. He should be able to just start typing.

https://github.com/user-attachments/assets/2fc78e2f-938c-41c7-8144-578599a95867

**Comment by BoppLi** [comment]
>  the flyout closes when pressing space, although it should be possible to search values with spaces

This seems to be broken for a while now, I went back to 9.7. and there it already misbehaved. we have to search further in the past when it happened. 
Let's discuss this tomorrow

**Comment by BoppLi** [comment]
All feedback has been implemented. see
- **docs(OnyxSelect):** create [example of custom search](https://storybook.onyx.schwarz/?path=/story/form-select--with-custom-search) + [point out the normalizedIncludes method](https://storybook.onyx.schwarz/?path=/docs/form-select--docs)
- **refactor(OnyxSelect):** omit `showfocus` which is only used to control OnyxSelectInput
- **refactor(OnyxSelect)!:** remove redundant `manualSearch` property [in favor of inferring the managed state of searchTerm](https://storybook.onyx.schwarz/?path=/story/form-select--with-search)
- **refactor(OnyxSelect):** extend useManagedState to inform wether the prop `isManaged`
- **fix(OnyxSelect):** [re-focus on miniSearch when opening the select a second time](https://storybook.onyx.schwarz/?path=/story/form-select--with-search)
- **fix(OnyxSelect):** don't select on `space` [if a search is included](https://storybook.onyx.schwarz/?path=/story/form-select--with-search)
  - **refactor(createComboBox):** ignore space as select key only when a search is included, independent on `isMultiple`

as well as additional findings that were done for
- #1563
- **fix(OnyxSelect):** add spacing before group names when
  - [combined with search](https://storybook.onyx.schwarz/?path=/story/form-select--grouped-options&args=withSearch:!true;open:!true)
  - [combined with check all](https://storybook.onyx.schwarz/?path=/story/form-select--grouped-options&args=multiple:!true;withSearch:!false;open:!true;withCheckAll:!true)
- **fix(OnyxSelect):** [prevent multiple "Select all" occurrences if options are grouped](https://storybook.onyx.schwarz/?path=/story/form-select--grouped-options&args=withSearch:!false;withCheckAll:!true;multiple:!true)

**Comment by larsrickert** [comment]
I approved it :) Only one small Storybook bug I noticed:
The Storybook control for single select is object, should we change it to text?

![Image](https://github.com/user-attachments/assets/431159e5-45ca-4415-ab64-70f68e4673c5)

**Comment by BoppLi** [comment]
> I approved it :) Only one small Storybook bug I noticed: The Storybook control for single select is object, should we change it to text?

https://github.com/SchwarzIT/onyx/issues/1701
