### ISSUE TITLE
Fix OnyxSelect search input behavior

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1466]
1. Open [this example](https://playground.onyx.schwarz/#eNp9kk1vwjAMhv9KlPNWDtuJwaRt4rAJDTR2W6YpFANhaRIlLh9C/Pc5aUs5dKhSZedx3zqvfeRPzmXbEnifD0LulUOmpVkNBccgOAuApXsURhXOemRHNjGH/Qw05MhObOltwQQPCm8tnQv+IIwwuTUBmXWoKGBD9iUMY8f4YlS8lboEwfsUSuc0hTcN0nIOukLUVUSRnBLv+n4uDT3dAs81axT+0wjo5W4O3h+6dWYXPGkJ8023HPQqs8gaShAKpyUCZYwNWosqvaRGho72ksqAPE0syRFVAcd1xZjiqryh/dpGgnXUEPphDmurF+AJTtssy7KmZqdwPQPp83XMe9TeoHfuld/QiGlWS7XKNsEa2oBkkOC5LZzS4CfNH/utdVJru3tLZ+hLOFuWryH/7TjfBFqLaOTUQwC/vZw3Sr8CMiLi0ewd9hSfYWEXZVyBK/ADgtVl7LGeeWkW1PZFXer2Ne2uMqvPMNojmNBcKjbabhitRQkvV67etnuX3de7cCIXf7bgoyYZGI0NyE9/eH0W3w==)
2. open the select
3. type in ABC
4. move the cursor BEFORE A
5. Type in DE
=> expected result: "DEABC"
=> actual result:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/b79d43e5-8ecb-4de0-bd53-4bb60ba5cc3d)

Somehow, the cursor jumps to the end of the string after typing "D". this also happens when deleting part of the search value.

OnyxMiniSearch itself is not a problem, it only happens inside the select

**Comment by P-yiush07** [comment]
can i work on this ?

**Comment by larsrickert** [comment]
> can i work on this ?

Hey 😄  Yes sure, contributions are always welcomed!
