### ISSUE TITLE
Fix scroll bug in OnyxNavBar mobile mode when you have too many NavItems

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#1483]
- [x] When we have too many nav buttons in mobile mode of the nav bar and the screen is not high enough a scrollbar should appear.
- [x] add 2rem to max width of mobile nav items
- [x] Adjust mobile context menu to be able to scroll
  - [x] app version changes: same optics as nav items (just not clickable).
  - [x] Fix duplicate border in mobile context menu
  - [x] Screenshot test is missing -> https://github.com/SchwarzIT/onyx/pull/1540
  - [x] create UX "adjust" ticket for the mobile app version
    - #1552

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/b758b7a2-1c73-46ca-a306-53d319af664e)

- [x] fix mobile nav parent highlighting
  - [x] parent is hidden if parent is not clickable -> add storybook example
  - [x] in the drilled-down level, the parent should not be highlighted if a child is active

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/dc239cc5-1341-4551-966c-efabf8a6ab40)

**Comment by BoppLi** [comment]
For review, show
1) [overflowing menu content](https://storybook.onyx.schwarz/?path=/story/navigation-navbar--with-overflowing-mobile-content&globals=viewport:xs)
  - open menu: it now scrolls with many nav buttons
  - open "Item 2": it scrolls with many nav items/children
  - open context menu: it scrolls + the app version is not sticky anymore
2) [updated Storybook example](http://localhost:6006/?path=/story/navigation-navbar--default&globals=viewport:xs)
  - Item 2 is not highlighted when opened, only its active child is highlighted
  - Item 3 is hidden when opened
