### ISSUE TITLE
Fix playground doesn't seem to use the selected onyx version

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#1489]
### Repro steps

1. Open this [Playground example](https://playground.onyx.schwarz/#eNp9Uk1v1DAQ/Ssjn3fXQnBaQsWHKgEHWlEuSJaQiWcTF8e27EnYarX/nbGTbQNCvXnmvZl57yUn8S7G3TSi2Ismt8lGAqd990YJykpARhrjlfJ2iCERnODGPxw/ojbOetzU6o4wRkxwhkMKAyiRLW0DA0q8Vr6R81bewQXhEJ0m5AqgMXaC1umc+VoZ2HbJmm0bPGnenpSoNCauj4It9P4Fo7dOP3QpjN40ck25jMWr72GEVntAYwmoR2iDQQi+vh0eCLQ3bBLnhp0QEubRUYYeE+4aWcyvVCxmlwsAC1TPr7FGsjl+NXJlWXmxEXOS20HH3X0OnnM/lQG1ABz6Hmqn9J6i3HPVE8W8l7I1nmcNst6080jSx0FeqG9/Imm+nklab/DITCXKvrPyZ75PmQM+2O6f620YonWYbiLZ4P9WoZ0Lvz/XHqURN5d+22P76z/9+7wIvuUwMU2oxCNGOnVIM3x99wWP/H4Eh2BGx+xnwK+YgxuLxpn2nr8+y17xqtpPNUzru2/5+kjo88VUEVrTqHwl+Nf/8Iz1J7kvd69WKf6YMJWdHGD5uJnE+Q/40Rr9)
2. The example was created with the `alpha` version of onyx, but instead the newest version is selected
3. When the version is manually changed to an `alpha` version, the `OnyxStepper` shouldn't be rendered, as it didn't exist in that version. Its HTML is rendered anyway, even tough without the correct styling.

### Expectation

- The selected version should sync to the URL and loaded when a playground is opened with this link
- The selected version of `sit-onyx` should be actually loaded (e.g., `OnyxStepper` shouldn't be rendered and give an error when an alpha version is selected).

**Comment by JoCa96** [comment]
@larsrickert Would it be possible (without too much effort) to implement a test for this?

**Comment by larsrickert** [comment]
> @larsrickert Would it be possible (without too much effort) to implement a test for this?

Sure :) #1689
