### ISSUE TITLE
Implement theme distribution

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1490]
### Acceptance criteria

- [x] Pipeline is extended to extranct the Figma theme tokens
- [x] Explain the concept in the docs + add an example

### Out of scope

- #764 
- #1493

### Definition of Done

- [x] Docs are updated: how to import a theme
- [x] updated version + documentation is deployed
- [x] Set task to `In Approval`

**Approval**

- [Deployed Docs](https://onyx.schwarz/development/theming.html)
- [Storybook Theme Selection on Topbar](https://storybook.onyx.schwarz/?path=/docs/buttons-button--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @BoppLi

**Comment by jannick-ux** [comment]
We have to check the color palettes with the implementet color-values. The colors for Lidl and Kaufland seems to be incorrect in the storybook component. 
An extra meeting for this would make sense here. Who is the dedicated developer here?

**Comment by larsrickert** [comment]
> The colors for Lidl and Kaufland seems to be incorrect in the storybook component.

We imported them from Figma :) I sent you a meeting to check this

**Comment by jannick-ux** [comment]
The reason was my private monitor, that displayed the colors incorrectly.
