### ISSUE TITLE
Implement blueprint with onyx

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1497]
[Feature 645153](https://dev.azure.com/schwarzit/schwarzit.odj.enterprise-blueprints/_workitems/edit/645153): Create intermediate release for Vue Blueprint v3 including Onyx

- [x] Docs for old blueprint v2 should still be deployed on a subdomain
- [x] Replace Core UI with onyx
- [x] Document how Core UI and onyx can be used at the same time
- [x] Mention old version in documentation -> How to use the old v2 cli

**Comment by mj-hof** [comment]
All the efforts for that tickets need to be booked on the blueprint solution. If you have questions, please contact me :)
