### ISSUE TITLE
Fix OnyxUserMenu captures click events before they reach the actual target

### ISSUE THREAD

**Issue by markbrockhoff** [SchwarzIT/onyx#1518]
### Version

1.0.0-beta.0

### Description

Hi, while trying to use the OnyxUserMenu I encountered the following bug:

Whenever I try to click something inside the menu it just closes, blocking any interaction with the elements inside of it.
Using the keyboard to interact with the element works as expected but click events seem to be blocked at some point.

### Reproduction steps

Here's a playground reproducing the issue. The example is basically the same as in the [docs](https://onyx.schwarz/development/theming.html#dark-mode), just without vueuse.

[Playground](https://playground.onyx.schwarz/#eNp9Uk1PAjEQ/SuTekATPg56QjAB5ACJYERvTUyzDLDQbZu2u2II/91pF9g1IfTUznsz895MD2xgTLvIkXVZzyU2NR4c+tyAFGrd58w7zl64SjOjrYcDzNXvfiaKobDNeP9yaN9Q5eVrpKW2i2SDGYbgxGMGR1hZnQFnLvUtTSTOnmsFLa4qCgmJKFeJVs5DUtWDfqDeN5bC7hoPxOl1Sr2kjh7UyUjhkV4AvUolCGNaSmRIXsZ7QSQMoWgK6FwS4Y5aetz7gUVxAk+Vzh4hp8up1lRvFLxqknvhntjXZlC0Mr1ESXk1R5xBp2rUqXc6i+v8txU5pS8K1FDWpEWR/lW6bm+dVrTNQ8gI/TKTSrRz41MaKWddiEjAhJT6Zxpj3ubYPMdJXbK7Et862l2XLu8WSWhBDi6YF3aNvoTHixnNsQaS+VwS+wb4gU7LPGgsacNcLUl2jRfVTuK3SdX60433HpU7mwpCA/MY+fEnjW5Yr+Q+tp9iHldHmuJ3gTbUpAGGwTrPjn95Lg0B)

### Confirmations

- [X] I have checked that there is not already a bug report for my issue.
- [X] I confirm that are no sensitive information included in this bug report. e.g. credentials, internal project details (for employees of the Schwarz Group) etc.

**Comment by JoCa96** [comment]
Thanks for reporting! Will be fixed soon.

**Comment by markbrockhoff** [comment]
Just as a note: It looks like not only the user menu is affected also a normal OnyxNavButton seems to not trigger any event when clicking it. Maybe the issue arrises from the Flyout which wrapps all of them?
