### ISSUE TITLE
Implement guide for SCU/onyx hybrid apps

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1549]
- write guide how you can integrate core-ui in an onyx blueprint
  - [x] in Blueprint docs
  - [x] explain in the guide that dark-mode is out of scope
- ~~provide stylesheet for mapping core-ui colors with onyx (if possible, detect in CoreUI if onyx is used (e.g. by doing something like :has(.onyx-app) in CSS and apply the stylesheet then so no manually work is needed for the project)~~
- Follow up: #1682

**Comment by larsrickert** [comment]
Live on: https://vue-blueprint.schwarz/migrations/v3.html#coreui-hybrid-mode (only accessible inside Schwarz VPN)

We decided to not map any CoreUI tokens to onyx to:

1. keep it simple
2. do not make "hybrid mode" too pretty so users want to fully migrate to onyx asap
3. not change CoreUI visuals
