### ISSUE TITLE
Implement 'strip step' and 'precision' feature for the OnyxStepper

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#1587]
### Why?

FoUp: #1348 

We want to support 'strip step' and 'precision' property for stepper component that is optimised for entering numbers.

### Design

[Figma](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=5041-2580&t=zdXvmCyp6tpZ7T07-4)
[Figma 2](https://www.figma.com/design/EBi98T51T9fGfjrYYfsulg/onyx---Archive?node-id=3427-75828&t=Hm9mcl2OKFJa9QN9-0)

### Acceptance criteria

- [x] can optionally put into "strip step" mode so that when manually entering values that do not fit the step size, the change is ignored
- [x] can optionally define a "precision" for the displayed value to always display the given number of decimals places, e.g., "3.00"
- [x] The [spinbutton](https://www.w3.org/WAI/ARIA/apg/patterns/spinbutton/) aria pattern is applied.
- [x] Disable buttons and styles for min/max-level

### Definition of Done

- The following component requirements are implemented:  
- [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] example usage added to `apps/alpha-test-app/src/views/FormDemo.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/form-elements-stepper--default)
- [x] approved by dev @JoCa96 

### Implementation details

- implemented using the generic [FormElement](https://storybook.onyx.schwarz/?path=/docs/support-formelement--docs) support component
- Consider the advice: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#accessibility

### Reference implementations

- [Element plus](https://element-plus.org/en-US/component/input-number.html)

**Comment by JoCa96** [comment]
@ChristianBusshoff Right now we always round based on the precision, which kind of makes `stripStep` useless. Also, IMHO, it would be preferable to not change the user-input by default.

**Comment by larsrickert** [comment]
My original intention of this ticket was that the stepper supports 3 properties: `step`, `strictStep` and `precision`

- `step`: Like the native step property of an HTML input. Defines how the value is changed when clicking the + or - button / arrow up/down. But every number can be entered (if `strictStep` is disabled), even if it does not match the step
- `strictStep`: If enabled, entered values must match the defined `step`. If invalid numbers are entered, they are either ignored or an error is shown
- `precision`: Has no effect on the actual value. Is only used for defining how many decimal places are displayed(`.toFixed()` method) . Example: If `modelValue` is `3` with a precision of `2`, the stepper will show `3.00` although the technical value is just 3
