### ISSUE TITLE
Implement removal and linting of native event name usage

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#1603]
### Why?

Currently, we are re-emitting events like `click` or `change`.
This creates complications and confusion for our users:
- the emit names are already reserved by native HTML events
- the emit payload is not compatible
- the custom emits don't work with Vue [event](https://vuejs.org/guide/essentials/event-handling.html#event-modifiers) and [key](https://vuejs.org/guide/essentials/event-handling.html#key-modifiers) modifiers
- there is a performance overhead of listening for the native events and re-emitting them
- native events don't behave like Vue events (bubbling, etc.)

### Acceptance criteria

- [x] all onyx emits with native event names have been removed or renamed
- [x] a lint rule enforcing non-native event/emit name collisions is added. (can be a follow-up ticket)
- [x] a storybook helper/util is provided that allows relevant events to be logged

### Definition of Done

- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly

**Approval**

- Docs: New Storybook util is documented here: https://onyx.schwarz/development/packages/storybook-utils.html#withnativeeventlogging 
- Storybook: Most components now have an `Relevant HTML events` section, where native HTML events are documented: e.g.: 

1. Go To https://storybook.onyx.schwarz/?path=/story/form-input--default 
2. Open the "add-on sidebar" if necessary
3. Scroll to the `Relevant HTML events` section and you will find the documented elements

- [x] approved by dev @larsrickert 

### Implementation details

Make use of `eslint-plugin-vue/lib/utils`:

```js
const utils = require("eslint-plugin-vue/lib/utils");
```

#### Reference implementations

See the following as examples for similar lint rules:
- [vue-require-explicit-emits](https://eslint.vuejs.org/rules/require-explicit-emits.html#vue-require-explicit-emits)

**Comment by MajaZarkova** [comment]
- [PR open](https://github.com/SchwarzIT/onyx/pull/1799)
- The PR doesn't have a changeset yet
- A follow up ticket should be created regarding this [comment](https://github.com/SchwarzIT/onyx/pull/1799#discussion_r1745203585)
- There is a replay on the other two comments with the issues I have encountered.
- The last point of this ticket (the part in Implementation details) is not implemented
