### ISSUE TITLE
Implement visual feedback in clickable vs non-clickable group-navItem

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1614]
Change the pointer cursor in the nav bar for a NavItem and ContextArea into arrow cursor 

[Example](https://storybook.onyx.schwarz/?path=/story/navigation-navbar--default&globals=viewport:md) - Item 2 is clickable (has a link itself), but Item 3 only has children but is not itself clickable.
Right now, both look exactly the same on desktop - both have cursor-pointer etc.
On mobile, we have a distinction but this would not work on desktop.
![Image](https://github.com/user-attachments/assets/ff4fb1f4-4ec0-4ee1-8342-4f007e7cf7f3)

**Comment by mj-hof** [comment]
Is a indicator for nested items needed?
