### ISSUE TITLE
Implement LB 🐣 Part 1 / 2

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1623]
## Part 1: core-ui.schwarz

hidden button in https://core-ui.schwarz/development/about-onyx, when you click it, open a popup with something like

![Image](https://github.com/user-attachments/assets/6ee05ec0-4587-4c12-8cc3-b39b91f26bc3)

![Image](https://github.com/user-attachments/assets/1024a366-5b2c-47e9-bce6-3beafd2e61db)

**Approval**

Deployed docs: https://coreui-showcase-qa.apps.02.cf.eu01.stackit.schwarz/development/about-onyx -> click the big onyx logo :)
- [x] approved by designer @jannick-ux 
- [x] approved by dev @MajaZarkova 

## Part 2: see

- #1768

**Comment by mj-hof** [comment]
Please let me know what you have in mind 😄

**Comment by BoppLi** [comment]
[Pull Request 626691](https://dev.azure.com/schwarzit/schwarzit.core-ui/_git/schwarz.core-ui/pullrequest/626691)
: docs: implement easter egg
