### ISSUE TITLE
[Bug]: Attrs on OnyxPageLayout are not applied to default slot

### ISSUE THREAD

**Issue by markbrockhoff** [SchwarzIT/onyx#1650]
### Version

1.0.0-beta.18

### Description

Hi, not exactly sure if this is a bug or an intentional decision but I noticed that attributes (e.g. classes) added to the OnyxPageLayout are not added to the main tag wrapping the default slot but rather the div wrapping all slots.
This requires users to wrap the content inside the default slot again every time they need to apply styles like e.g. a grid to it.

Maybe it would be good to think about if this is something which could improve the DX of onyx.

### Reproduction steps

https://playground.onyx.schwarz/#eNqtVE2P1DAM/Ssm5+2MFjiVMhKglQABO4K9IFVCUeO2WdIkStz50Gj+O0663Rmh2T0gDpVsP9t5fol7EO+8X2xGFKWoYhO0JzDSdm9rQbEWEJFGv6qtHrwLBAe4tfvdWnb4Re7dSHCENrgBahE1FY6xWrypbbWcWnEhO4SDN5KQPYDqRVHAXa8jbLUxIJUC6hG6oNlw2fbcnknk/poimha0jYRSgWtzRuMsoaWYfE1QFFPrv7g1RsbIg6TetcgpD0kfuZfRFkEnvL9mdM0HdsGNVlXL85S5zK9+uhEaaQEVHzmxUAjOZttgSyCtYsFwCugNQsA4GqbZY8BFtUxCcqvc/8Qzi/QgzFeUdttrk3qwRNJ7ozGeFGpcCNiQ2T8x88xW6c3l8f9ZgP8qQRKBKT4lR7U8ezLsRtqzIrFxHhVHFlmKQypWOnLevszq8MODbBRzedE4Mw42liBHchfw4LYMXrchfRMufQkvAw7sHfNLToevxBXvAz+7VneL++gsr0smUIvGDZ4vLNx60s7yzpQTtYRJY9z2c45RGPFqjjc9Nr8vxO8j70/Jxpplw7DBWjxiJEOHNME3P77hju1HcHBqNJz9DPgdI4uROE5p7/mmmfZZXmb7KS+6tt1dvNnxksV5qEQ0ZR5zfi34n/HhmdFPdF8tXuc61pNV/LXBkHqygOkGIonjH54Shmw=

### Confirmations

- [X] I have checked that there is not already a bug report for my issue.
- [X] I confirm that are no sensitive information included in this bug report. e.g. credentials, internal project details (for employees of the Schwarz Group) etc.

**Comment by larsrickert** [comment]
@markbrockhoff Good hint, thanks! We already have an internal composable to achieve this :)
I created PR #1652 for this

**Comment by larsrickert** [comment]
After discussion with @JoCa96, we decided that the current behaviour is the intended one and we do not plan to change this currently. If we get more feedback on this in the future, we will consider re-opening this issue :)

The main reason is that the user benefit is very minimal (one less `<div>` needed) while it might cause unexpected behaviour on the other hand. E.g. setting any styles on the page layout itself would no longer be possible / when setting attributes on a component (class, data-testid etc.), you usually expect it to be applied to the same component.
