### ISSUE TITLE
Implement CoreUI info tile about onyx

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#1682]
### Why?

Follow up for #1549. We want to announce to our CoreUI users that onyx is now beta version and the onyx based v3 Vue Blueprint has been released.

### Acceptance criteria

- [x] the CoreUI showcase shows a global info tile below the top bar that informs the user about the onyx beta + v3 Vue Blueprint (maybe with link to the teams announcement or page with further information / FAQ)
- [x] the global info tile can be dismissed which is saved in the localStorage so it does not show up again when reloading the page (optionally the message is moved to the notification center of the top bar)
- [x] an announcement in the CoreUI teams channel is made
  - we can use that chance to mention the new inner-source accessibility of the core-ui repo :)
- [x] the hybrid mode is mentioned: https://vue-blueprint.schwarz/migrations/v3.html#coreui-hybrid-mode

### Definition of Done

- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed

**Approval**

- [Home Page of Showcase](https://core-ui.schwarz), see:
  - Global Info tile
  - onyx link in top-bar context area
  - faq entry
  - Martin as product owner
- [Info Page explaining onyx + CoreUI + Vue Blueprint strategy](https://core-ui.schwarz/development/about-onyx)
- [Link to the announcement](https://teams.microsoft.com/l/message/19:7adba8e3c481432fb8c3822444d635b2@thread.tacv2/1722952786076?tenantId=d04f4717-5a6e-4b98-b3f9-6918e0385f4c&groupId=834e63c5-22ad-4e57-92e5-8092280f8af6&parentMessageId=1722952786076&teamName=CoreUI&channelName=General&createdTime=1722952786076)
- [x] approved by designer @mj-hof 
- [x] approved by dev @larsrickert

**Comment by BoppLi** [comment]
Announcement text:

### Vue Blueprint, onyx and what it has to do with CoreUI

<a href="https://onyx.schwarz" target="_blank">onyx</a> - the new Schwarz design system and
        component library, is the successor of CoreUI.

onyx is based on Vue.js (see
        <a
          href="https://principles.schwarz/engineering-principles/software-engineering-foundations/programming-languages/use-vue-js/"
          target="_blank"
        >Principles@Schwarz</a>) and built from the ground up with focus on modern implementation patterns, design, developer experience,
        accessibility as well as improvements based on learnings from CoreUI over the past few years.

Read more on the future of CoreUI in regards to onyx <a href="/development/about-onyx">here!</a>

**Comment by BoppLi** [comment]
[Pull Request 621614](https://dev.azure.com/schwarzit/schwarzit.core-ui/_git/schwarz.core-ui/pullrequest/621614): docs: inform about CoreUI's future, onyx and the Vue Blueprint

![Image](https://github.com/user-attachments/assets/a9f792fc-54cc-476d-a2e8-a3047ac2d75c)
