### ISSUE TITLE
Fix missing matrix screenshots for OnyxRadioGroup

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1697]
https://teams.microsoft.com/l/message/19:3a7010e95b8749edac6271ea346a7bc4@thread.tacv2/1722925096614?tenantId=d04f4717-5a6e-4b98-b3f9-6918e0385f4c&groupId=969ca3b3-9c78-411f-8629-eb770bbfdc7b&parentMessageId=1722925096614&teamName=onyx&channelName=Developers&createdTime=1722925096614

![Image](https://github.com/user-attachments/assets/095f2aae-7544-4cfe-b551-7d982a3a83fe)

**Comment by larsrickert** [comment]
@jannick-ux I renamed the `headline` property to `label` for the radio and checkbox group so its uniform with our other form components. Can you also rename it in Figma?
