### ISSUE TITLE
Fix small layout jump on invalid OnyxInput / OnyxFormElement

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#1731]
the following example shows an OnyxInput with a pattern validation which needs an email with @xxx.x - before the last letter is typed, the error exists, even though invisible (because of user-invalid) and as soon as it is solved you see a little jump in the component.

https://github.com/user-attachments/assets/32b5b440-03ff-45e6-ba39-44e8a3148b40

**Comment by larsrickert** [comment]
@BoppLi Could you please provide a reproduction snippet? I can not reproduce it, the input has a 64px height for me

**Comment by MajaZarkova** [comment]
Waiting for reproduction code from Linda

**Comment by JoCa96** [comment]
We can accept this workaround to avoid the layout jumping.
Extended the acceptance criteria of #573 to fix the root issue.
