### ISSUE TITLE
Fix select bugs

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#1734]
OnyxSelect bugs I noticed when working on #1722:

1. Clicking the gap between label and icon or clicking on the padding does not open the select. Only when clicking **exactly** on the label or icon

![Image](https://github.com/user-attachments/assets/6a1d0ff1-3bfd-4604-8a62-3f0ec105302d)

2. When changing the value programatically, the page jumps (because the select tries to scroll into view) although its not opened

https://github.com/user-attachments/assets/322faac2-ad46-4f4e-a91b-649aa914f14d

**Comment by larsrickert** [comment]
@MajaZarkova When opening the select, it does scroll but not "far enough" so the select option is not visible


![Image](https://github.com/user-attachments/assets/0f9ae163-36d3-436d-91ff-7b4000739777)

**Comment by MajaZarkova** [comment]
> [@MajaZarkova](https://github.com/MajaZarkova) When opening the select, it does scroll but not "far enough" so the select option is not visible
> 
> ![Image](https://github.com/user-attachments/assets/0f9ae163-36d3-436d-91ff-7b4000739777)

Follow up bug ticket #1781
