### ISSUE TITLE
Concept basic datepicker

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#1817]
Overall image of date- and timepicker component
Basic approach for datepicker in cooperation with development

**Comment by larsrickert** [comment]
As reference: It would look like this if we use our OnyxInput with the default HTML datepicker

![Image](https://github.com/user-attachments/assets/3d54d1e1-eae3-46f5-80b8-05b556eb0484)
![Image](https://github.com/user-attachments/assets/c15235cd-f107-4c08-8437-ef8cf3b64a2c)

**Comment by larsrickert** [comment]
@SchwarzIT/onyx-ux Idea for our future onyx datepicker:
Show current user timezone and optionally be able to change timezone
