### ISSUE TITLE
Implement OnyxSwitch

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#191]
### Dependencies
- [ ] #244
- [ ] #368 

### Why?
A switch is visually and semantically distinct from a checkbox.
The switch allows switching something *on* or *off*, rather than selecting something.

### Design
[Figma Design](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=711%3A12812&mode=dev)

### Acceptance criteria
- [x] can be toggled on click and updates modelValue
- [x] the toggling is animated
- [x] the following styles are implemented:
  - [x] :hover
  - [x] :focus-visible
  - [x] :disabled
  - [x] :checked
- [x] can be used with or without label
- [x] must accessible even without label (using aria-label)

#### Out of scope
- Support number and string values
- Ability to change on/off icon

### Definition of Done
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
  - [x] _approved by dev @larsrickert 
- [x] Storybook can show the feature
- [View in StoryBook](https://onyx-storybook-prod.apps.01.cf.eu01.stackit.cloud/?path=/docs/components-onyxswitch--docs)
  - [x] _approved by designer @jannick-ux 

### Implementation details
- Implement using a checkbox (See reference implementations:  [ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/))
- `hideLabel` uses [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) instead of a visual label

```ts
type OnyxSwitchProps = {
  modelValue?: boolean;
  label: string;
  hideLabel?: boolean;
  disabled?: boolean;
  required?: boolean;
}
```

#### Reference implementations
- [ARIA APG](https://www.w3.org/WAI/ARIA/apg/patterns/switch/examples/switch-checkbox/)
- [Vuetify](https://vuetifyjs.com/en/components/switches/)
- [Nuxt](https://ui.nuxt.com/components/toggle)
- [KendoUI](https://www.telerik.com/kendo-vue-ui/components/inputs/switch/)

#### Applicable ARIA Pattern
- https://www.w3.org/WAI/ARIA/apg/patterns/switch/

**Comment by MajaZarkova** [comment]
There is no UX design for errorMessage, or am I missing something?

**Comment by JoCa96** [comment]
@MajaZarkova Good point, I removed that point :)

**Comment by MajaZarkova** [comment]
No Figma design for invalid disabled state

**Comment by jannick-ux** [comment]
![Image](https://github.com/SchwarzIT/onyx/assets/152376364/4aa2a504-3d61-46f5-880b-5ef10c12ae0f)

In case of a error state, the padding on the left is off for a couple of pixels.
