### ISSUE TITLE
Fix storybook utils event logger

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#2012]
When using our `withNativeEventLogging` Storybook utility, the actions will be logged twice when the `@storybook/addon-interactions`addon is also active/used.

Without the interactions addon, its fine

**Comment by JoCa96** [comment]
@larsrickert I am unable to reproduce the issue

**Comment by JoCa96** [comment]
In this case, the double logging was caused by using `v-bind="$attrs"` without `defineOptions({ inheritAttrs: false })`. This caused the Vue event listener to be bound twice.

=> No issue on our side.
