### ISSUE TITLE
Implement OnyxTabs

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#2018]
### Why?

We want to offer a tabs component where content can be grouped in tabs for structuring page or sidebar content.

### Design

[Figma](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=7162-15700&t=w1vkWbCstQZGcKGn-4)

### Acceptance criteria

- [x] the design is implemented
- [x] only one tab can be active at the same time
- [x] a tab can be disabled
- [x] arbitrary custom content can be placed in the tab (e.g. icon, badge etc.)
- [x] the [accessibility pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) is implemented

#### Follow up tickets

- #2079

### Implementation details

- inactive tabs should not be rendered (v-if) to increase performance and unwanted side-effects (e.g. onMounted triggered although the content is not visible)
- we can use provide/inject to inject which tab is active
- tab value/ID should allow any `PropertyKey` (string, number, symbol)

##### Option 1 (recommendation by @larsrickert):

| Advantages                                                    | Disadvantages                                   |
| ------------------------------------------------------------- | ----------------------------------------------- |
| Tab and panel content are grouped together (less error prone) | Unable to have same content for multiple panels |

```vue
<script lang="ts" setup>
const activeTab = ref("tab-1");
</script>

<template>
  <OnyxTabs v-model="activeTab">
    <OnyxTab value="tab-1" label="Tab 1"> Content for tab 1... </OnyxTab>

    <OnyxTab value="tab-2" label="Tab 2">
      <template #tab="{ label, active }">
        {{ label }} is active: {{ active }}
        <OnyxBadge dot />
      </template>

      Content for tab 1...
    </OnyxTab>
  </OnyxTabs>
</template>
```

##### Option 2:

| Advantages                                      | Disadvantages                                                                                              |
| ----------------------------------------------- | ---------------------------------------------------------------------------------------------------------- |
| Panel allows shared content for multiple panels | v-if has to be done on every panel by the user                                                             |
|                                                 | tab and panel for the same tab are separated in the code                                                   |
|                                                 | user must make sure that tab and panel IDs are matching (can lead to unexpected behavior if changing them) |

```vue
<script lang="ts" setup>
const activeTab = ref("tab-1");
</script>

<template>
  <OnyxTabs v-model="activeTab">
    <OnyxTab value="tab-1">Tab 1</OnyxTab>
    <OnyxTab value="tab-2">
      Tab 2
      <OnyxBadge dot />
    </OnyxTab>

    <template #panel>
      <div v-if="activeTab === 'tab-1'">Content for tab 1</div>
      <div v-if="activeTab === 'tab-2'">Content for tab 2</div>
    </template>
  </OnyxTabs>
</template>
```

##### Option 3:

| Advantages                    | Disadvantages                                                                                              |
| ----------------------------- | ---------------------------------------------------------------------------------------------------------- |
| Clear/separated panel content | Unable to have same content for multiple panels                                                            |
|                               | tab and panel for the same tab are separated in the code                                                   |
|                               | user must make sure that tab and panel IDs are matching (can lead to unexpected behavior if changing them) |

```vue
<script lang="ts" setup>
const activeTab = ref("tab-1");
</script>

<template>
  <OnyxTabs v-model="activeTab">
    <OnyxTab value="tab-1">Tab 1</OnyxTab>
    <OnyxTab value="tab-2">
      Tab 2
      <OnyxBadge dot />
    </OnyxTab>

    <template #tab-1>Content for tab 1 </template>
    <template #tab-2>Content for tab 2 </template>
  </OnyxTabs>
</template>
```

#### Reference implementations

- [Nuxt UI](https://ui.nuxt.com/components/tabs)
- [Element Plus](https://element-plus.org/en-US/component/tabs.html)
- [Shadcn](https://www.shadcn-vue.com/docs/components/tabs.html)

#### Applicable ARIA Pattern

[Tabs patttern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)

### Definition of Done

- The following component requirements are implemented:
  - [x] skeleton
  - [x] density
  - [x] example usage added to `apps/demo-app/src/views/HomeView.vue`
- covered by tests
  - [x] functional tests (Playwright or unit test)
  - [x] visual tests (Playwright screenshots)
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Namings are aligned with Figma

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/docs/navigation-tabs--docs&args=modelValue:;type:search)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96

**Comment by larsrickert** [comment]
Keyboard support: Check if usage of next/previous sibling can be removed
