### ISSUE TITLE
Concept OnyxKey component

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#2023]
As a UI developer, I want to communicate to a user which keyboard shortcut they can use to trigger an action. Using this information, they can act immediately, without the need for a mouse click.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd):

> The `<kbd>` element represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device. By convention, the browser defaults to rendering the contents of a `<kbd>` element using its default monospace font, although this is not mandated by the HTML standard.

### Create "OnyxKey"
- [ ] _if needed_ variation
- [ ] density
- [ ] states
- [ ] dark mode
- [ ] keyboard support

### Functions
- [ ] Button sequence: `A`, then `B`, then `C`
- [ ] Multiple Buttons at once: `A` and `B` and `C` 
- [ ] Button options: `A` and `B` or `C`
- [ ] Optional:
  - [ ] Highlighting of currently pressed buttons
  - [ ] Global Overview dialog of keyboard shortcuts 

### Figma
- [ ] dev handover
- [ ] ux component

### documentation
- [ ] keyboard support
- [ ] property description
- [ ] textual documentation
- [ ] component grouping

### links for comparison

- [Browser Default](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd):
![Image](https://github.com/user-attachments/assets/a53c27f1-bc25-45c7-9c2d-7767f182fab1) 

- Variant in WaWi:
![Image](https://github.com/user-attachments/assets/3fd1feb3-292c-4ab8-a7f7-025027fbf071)

### Finalizing
- [ ] approved

**Comment by jannick-ux** [comment]
Not all checkboxes from the refined tickets are necessary to display in figma.
The outcome of the ticket is a cheat sheet component, that can be accessed via the user menu.
