### ISSUE TITLE
Define OnyxSupportButton

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#2053]
### Related to

- #1008

### Acceptance criteria

- [ ] A new created refined `Implement OnyxSupportButton` ticket
- [ ] Replaced `OnyxIconButton` in `packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/SortAction.vue`
- [ ] Ticket was created

**Comment by larsrickert** [comment]
See #2139
