### ISSUE TITLE
Define usecases of a potential generic "reveal component"

### ISSUE THREAD

**Issue by jannick-ux** [SchwarzIT/onyx#2070]
As a basis for multiple components (e.g. accordion) a generic "reveal component" could make sense. This could be used in multiple usecases embedded in multiple components. 
So a list with all the usecases should be created to see the full potential of this planned support component. 

- [ ] plain on page
- [ ] inside modal dialog
- [ ] Apply Button
- [ ] Edit Button (copy, duplicate, delete,...)
- [ ] Export (choose format)
- [ ] image switch to compare old/new image or article

**Comment by flubnau** [comment]
Create follow-up Ticketto show and discuss the reveal use cases
