### ISSUE TITLE
Implement OnyxTabs font styles and overflow

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#2079]
### Depends on

- #2018

### Why?

We want to offer multiple font styles for the `OnyxTabs` component and also make them horizontally scrollable if they exceed the max. available width (e.g. if many tabs are used).

### Design

[Figma](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=7162-15700&t=w1vkWbCstQZGcKGn-4)

### Acceptance criteria

- [x] Tabs should be horizontally scrollable if they exceed the max available width.
- [x] `h3` and `h4` font styles are implemented
- [x] The Storybook examples are updated to be more realistic
- [x] the bug is fixed that the tab content is not vertically centered if the tab is not selected
![image](https://github.com/user-attachments/assets/93777c6a-54c2-4788-bed9-a807f43dd10b)

#### Applicable ARIA Pattern

[Tabs pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/)

### Definition of Done

- covered by tests
  - [x] visual tests (Playwright screenshots)
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [x] Namings are aligned with Figma

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/navigation-tabs--many-tabs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @MajaZarkova

**Comment by jannick-ux** [comment]
scroll behavior and font size is fine. Thanks.
Just one finding here regarding the colors: The deselected tabs should have the "color/text+icons/neutral/medium" variable, but it seems like the have the "intense" one. The intense-value is exclusively for the selected tab.

**Comment by larsrickert** [comment]
> scroll behavior and font size is fine. Thanks. Just one finding here regarding the colors: The deselected tabs should have the "color/text+icons/neutral/medium" variable, but it seems like the have the "intense" one. The intense-value is exclusively for the selected tab.

The deselected already have the medium color, only the selected one has the intense one, see screenshot below. The difference is better visible in dark mode since medium and intense seem to be pretty similar in light mode

![Image](https://github.com/user-attachments/assets/e323d374-f7bb-4cc3-a327-fb19b5e76d1e)
![Image](https://github.com/user-attachments/assets/df5f333c-dcab-4382-87fb-8137aa6e39a6)

**Comment by jannick-ux** [comment]
Okay, in figma the deifference is more visible. But never mind, the important thing here ist, that the correct variable is used and it seems, this is the case.
The text colors will be optimized in the next couple of weeks to create more contrast. So we're on the fine side.

approved
