### ISSUE TITLE
Define option for automatic import for icons

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#2088]
Please check if there is a possibility via Figma API to import the icons from Schwarz Icon Library to our Onyx Library file with giving theme also a defined variable

If it works please check in copy of Onyx Libary file what happens with the icons page and icons that are used in components.

**Comment by JoCa96** [comment]
Works! Implement ticket: [#2309](https://github.com/SchwarzIT/onyx/issues/2309)
