### ISSUE TITLE
Implement OnyxCheckbox

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#220]
### Dependencies
- [ ] #244 

### Why?

A checkbox is an input control that allows a user to select one or more options from a number of choices.

### Design

https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=511%3A199&mode=design&t=28ZL5f0BYOVImIvs-1

### Acceptance criteria

- [x] Research how to best implement (check references)
  - using aria pattern?
  - using svg and invisible checkbox?
- [x] a checkbox with an optional label can be shown
- the following states are implemented:
  - [x] default
  - [x] hover
  - [x] focus-visible
  - [x] disabled
  - [x] invalid
  - [x] required
  - [x] optional
  - [x] checked
  - [x] indeterminate
- the following value types are supported:
  - [x] string
  - [x] number
  - [x] boolean
- [x] keyboard interaction is supported as documented in the ARIA pattern below

**Out of scope**

- an optional loading indicator can be shown, #393
- skeleton state, #379 
- truncation, #350 
- multiline text is supported (meaning newlines are rendered accordingly), #350 
- the following densities are supported (#349):
   - compact
   - default
   - cozy
- the following states are implemented (#339):
    - [ ] read-only 

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In review`

**Review**
 -  [View in Storybook](https://onyx-storybook-prod.apps.01.cf.eu01.stackit.cloud/?path=/docs/support-onyxcheckbox--docs)
 - [x] approved by designer @jannick-ux 
 - [x] approved by dev @JoCa96 

### Implementation details

- Make use of css pseudo selectors to render different states e.g. https://developer.mozilla.org/en-US/docs/Web/CSS/:indeterminate
- default truncation settings is: truncated + top-aligned 

#### Reference implementations

- [Nuxt UI](https://ui.nuxt.com/forms/checkbox)
- [Adobe Spectrum](https://spectrum.adobe.com/page/checkbox/)
- [Atlassian](https://atlassian.design/components/checkbox/examples)
- [WaWi](https://dev.azure.com/schwarzit/lidl.wawi-core/_git/lidl-wawi?path=/ui/components/src/components/WuxCheckbox/WuxCheckbox.vue)
- https://melt-ui.com/docs/builders/checkbox
- https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/examples/checkbox-mixed/

#### Applicable ARIA Pattern

https://www.w3.org/WAI/ARIA/apg/patterns/checkbox/

**Comment by jannick-ux** [comment]
Hey @larsrickert what is the difference between focus and focus-visible? What is the state of indeterminate?

**Comment by jannick-ux** [comment]
active state and selected state are the same for a checkbox, I guess. So we can get rid of active I suggest.

**Comment by larsrickert** [comment]
> Hey @larsrickert what is the difference between focus and focus-visible? What is the state of indeterminate?
Some examples:
- focus: User focuses/clicks on input so he can type into it (blinking cursor inside the input), see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus)
- focus-visible: User presses tab to focus a button/input so it usually gets a "focus-ring" / outline around it, see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible)
- indeterminate: Checkbox state with the typical "line" so its not checked but also not unchecked. See screenshot from Adobe Spectrum
![image](https://github.com/SchwarzIT/onyx/assets/67898185/9a732219-5bd2-4c22-a5d9-15a2d08d1182)

**Comment by larsrickert** [comment]
> active state and selected state are the same for a checkbox, I guess. So we can get rid of active I suggest.

Technically this are two separate states that occur in different scenarios so we need both:
- active: The user started to hold down the left mouse key
- selected: checkbox is checked and user does not need to hold his mouse key etc.

I added a comment in the ticket that they are visiually the same

**Comment by larsrickert** [comment]
read-only is out of scope for now since the native HTML checkbox input does not support read-only

**Comment by larsrickert** [comment]
> [@larsrickert](https://github.com/larsrickert)
> 
> * [ ]  `label` is optional, we must make it required for accessibility purposes. Instead the dev user should be able toggle its visibility via an additional attribute (you can use [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label))
> * [ ]  without `label` the input is not focusable

- I made the label required in #361
- the focus issue only seems to occur in firefox, I am not sure how we should handle this
