### ISSUE TITLE
Implement OnyxRadioGroup

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#222]
### Dependencies
- [ ] #244 

### Why?

A radio group is an input control that allows a user to select (only) one value from a number of choices.
The options must only be used inside the radio group and must not be used individually.

### Design

https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=626%3A15627&mode=design&t=rydWTxp4TqL9ckXI-1

### Acceptance criteria

- [x] multiple radio options can be put into the radio group
- [x] every radio option must have a label
- the following states are implemented:
  - [x] default
  - [x] hover
  - [x] focus-visible
  - [x] disabled
  - [x] invalid
  - [x] checked
- [x] at most one option can be selected
- [x] the radio group supports a vertical and horizontal layout
- [x] optionally a headline/legend can be shown above the radio group
- [x] keyboard interaction is supported as documented in the ARIA pattern below

_Out-of-scope:_
- densities
- loading
- errorMessage

### Definition of Done

[Storybook](https://storybook.onyx.schwarz/?path=/docs/components-onyxradiobuttongroup--docs)

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
  - [x] Approved by dev @larsrickert
- [x] Storybook can show the feature
  - [x] Approved by designer @mj-hof 

### Implementation details

- radio options are passed as property so we do not export the single radio option component so the user can not use it individually
- the value is typed generically

#### Reference implementations

- [Nuxt UI](https://ui.nuxt.com/forms/radio-group)
- [Adobe Spectrum](https://spectrum.adobe.com/page/radio-group/)
- [WaWi](https://dev.azure.com/schwarzit/lidl.wawi-core/_git/lidl-wawi?path=/ui/components/src/components/WuxRadioGroup/WuxRadioGroup.vue)

#### Applicable ARIA Pattern

https://www.w3.org/WAI/ARIA/apg/patterns/radio/

**Comment by JoCa96** [comment]
> - the following value types are supported:
>   - [ ] string
>   - [ ] number
>   - [ ] boolean

Can we just say that generic value is supported, or why exactly these three?

**Comment by JoCa96** [comment]
@larsrickert did you look into implementation options? Like do we implement this using native radiobuttons or custom implementation using the aria pattern? E.g. the nuxt example uses native radiobuttons.

**Comment by larsrickert** [comment]
> > * the following value types are supported:
> >   
> >   * [ ]  string
> >   * [ ]  number
> >   * [ ]  boolean
> 
> Can we just say that generic value is supported, or why exactly these three?

I don't think to type it as "any" or "unknown" because imho all other values doesn't make sense for a radio buttons like functions, arrays or objects

**Comment by larsrickert** [comment]
> @larsrickert did you look into implementation options and can give a preference? Like do we implement this using native radiobuttons or custom implementation using the aria pattern? E.g. the nuxt example uses native radiobuttons.

Not in detail...spontaneous I'd prefer native radio buttons

**Comment by BoppLi** [comment]
Note: [fieldSet](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset?retiredLocale=de) might be useful if the group has a title -> "legend"

**Comment by BoppLi** [comment]
tip: maybe we can add one radio button example to our form demo to verify the form behavior for a required radio group (=> blocks submit)

**Comment by larsrickert** [comment]
@JoCa96 Currently the modeValue is the whole option which can cause issues due to call by reference.
Also I think just having the value as modeValue is more convienient to work with.

**Comment by JoCa96** [comment]
@larsrickert `target.value` matches the `id`. `event.target` is the radio button and it's value is the options id

https://github.com/SchwarzIT/onyx/blob/d80d61eb6c007696bca6516993cf2bc5001cf94c/packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue#L29

**Comment by JoCa96** [comment]
@larsrickert and @mj-hof Please review!

**Comment by larsrickert** [comment]
@JoCa96 
radio group:
- only the first radio button can be focussed with tab
- (optional) we could use `v-bind="option"` in line 52 so we don't need to list all props

radio button:
- transition duration (line 106) is not included in the [durations defined by ux](https://onyx.schwarz/basics/motion.html#duration)

**Comment by JoCa96** [comment]
@larsrickert This is the default radio button behavior. Basically the act as one control: You tab in and can then change the selection using the keyboard.

**Comment by larsrickert** [comment]
Thanks for clarification :) Its approved
