### ISSUE TITLE
Update avatar styles to align with Figma

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#2268]
The avatar and AvatarStack styles currently differ from the [Figma design](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=5191-30549&m=dev).

The styles should be aligned:
- remove border for single avatar
- add primary border to avatars inside the AvatarStack

### Approval

- [Avatar](https://storybook.onyx.schwarz/?path=/docs/basic-avatar--docs)
- [Avatar stack](https://storybook.onyx.schwarz/?path=/docs/basic-avatarstack--docs)
- [x] approved by designer @jannick-ux 
- [x] approved by dev @JoCa96

**Comment by jannick-ux** [comment]
approved
