### ISSUE TITLE
Check Playwright screenshot performance

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#2291]
https://github.com/SchwarzIT/onyx/pull/2269#discussion_r1873454954

In #2064 we changed the matrix screenshot utility to not perform base64 string conversion of the screenshot and instead use Playwright mock routes. We thought this would increase performance of the screenshot tests.

However, after some quick local benchmarking, @larsrickert figured out that this change might actually be slower than the previous base64 conversion.

We should check/benchmark this and update our implementation if needed.

**Comment by JoCa96** [comment]
Probably makes sense to merge this with #2102

**Comment by JoCa96** [comment]
Merged into #2102
