### ISSUE TITLE
Define color themes

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#23]
Create the color themes for our product after the priority list

**Comment by jannick-ux** [comment]
Color themes for lidl, kaufland and twogo are finished from a ux-perspective. The themes of digits and onyx public are created but still under review an on hold. 
All the color values are already linked to the token system.
The color themes can be viewed [here](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Conception-%26-DEV-Exchange?type=design&node-id=0%3A1&mode=design&t=cokWllmNoJNi6SRH-1)
