### ISSUE TITLE
Implement OnyxAlertDialog

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#2306]
### Why?

We want to offer a pre-build alert dialog component that can be used to quickly implement common alert dialogs (e.g. delete or confirm dialogs).

Internally, the component uses our existing generic [OnyxDialog](https://storybook.onyx.schwarz/?path=/story/feedback-dialog--modal) component.

### Design

[Figma design](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/Onyx-Component-Library?node-id=8007-83120&t=yclnf4iT8J0sPy8j-4)

### Acceptance criteria

- [x] the component shows a required headline
- [x] a close "x" button is shown in the top right corner to close the dialog, should use the OnyxSystemButton
- [x] custom content can be passed via a slot for the main dialog content
- [x] a slot for custom right-aligned buttons can be used
- [x] an optional icon can be displayed. The icon and the color can be changed
- [x] ~~check if we want to have a dedicated group in the Storybook sidebar~~

### Implementation details

- the close "x" button might be considered to be implemented inside the `OnyxDialog` for all modals
- for the internally used OnyxDialog, both `modal` and `alert` property are always set

```ts
export type OnyxAlertDialogProps = Omit<OnyxDialogProps, "modal" | "alert">;
```

### Applicable ARIA Pattern

[Alert dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/alertdialog/)

### Definition of Done

- The following component requirements are implemented:
  - [x] density
  - [ ] example usage added to `apps/demo-app/src/views/HomeView.vue`

- Should be covered by tests:
  - [x] functional tests (Playwright or unit test)
  - [x] visual tests (Playwright screenshots)

- Make sure, that
  - [x] updated version + documentation is deployed
  - [x] Storybook can show the feature
  - [x] Storybook code snippet of new/changed examples are checked that they are generated correctly
  - [x] Namings are aligned with Figma

#### Approval

[Storybook](https://storybook.onyx.schwarz/?path=/docs/feedback-alertdialog--docs)

- Checked and approved by
  - [x] designer @jannick-ux 
  - [x] dev @MajaZarkova

**Comment by larsrickert** [comment]
Open UX questions:

1. The icon size is 72px but this is not a supported OnyxIcon size. Should we use 64px instead?
2. Is there a max width?
3. How does the content behave on smaller screens? E.g. does the icon move top the top?

**Comment by flubnau** [comment]
1. should align wth the limits so use 64px instead
2. i would go with a max-width for the alert. It's supposed to be used for smaller messages 
3. Would make sense to reduce the size depending to the screen. can we take 64, 48 (mid), 32 (small)?
4. use the right variable. I also updated the component in Figma
