### ISSUE TITLE
Create Search+Copy+Hover Feature for docs OnyxIconLibrary

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#242]
We want to create a search + copy feature in apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
\+ Improve the hover behavior, currently we use the standard browser feature which might take 3secs until a hover reacts.

- [x] Search
- [x] Copy
- [x] Hover

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/ba70f0d8-b6ab-4abf-8f28-c1c34b6d6cfa)

Downloading an svg is out of scope of this ticket.

**Comment by jannick-ux** [comment]
do we also need a svg-download feature here?

**Comment by jannick-ux** [comment]
Figma:
https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=662%3A5755&mode=dev&t=ei4JbTU8gYxuxFmN-1

**Comment by larsrickert** [comment]
> do we also need a svg-download feature here?

Currently we just linked to the files in GitHub for the download but I guess a download feature might be handy.
Maybe we could add a switch at the top to switch between "Copy code" and "Download SVG" when clicking?

**Comment by jannick-ux** [comment]
I Think a swith is not that handy. I think it would lead to a lot of unwanted downloads :D
A modal like this is the more understandable way for people
https://icons.stackit.schwarz/attachment

But this is no priority task for now I guess.

**Comment by BoppLi** [comment]
=> so we don't do a download for now, we just implement copy on click, right?

**Comment by BoppLi** [comment]
Note: aliases are empty for now. in the future, we will investigate how to import them from figma automatically.

**Comment by BoppLi** [comment]
Note: aliases are empty for now. in the future, we will investigate how to import them from figma automatically.
