### ISSUE TITLE
Define component density concept

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#246]
We need to discuss and review the concept for densities and touch areas of input components.

We have three densities:
- `compact` (usually 32px height)
- `default` (usually 40px height)
- `cozy` (usually 48px height)

Tasks:
- [x] It needs to be defined how click areas behave for the different densities in relation to the whole size:
  - for now there will not be any special rules
- [x] It needs to be defined how densities work with nested components/containers (e.g. table row, lists etc.)
  - container elements will provide a slot with matching density size. Borders sizes etc. will still be added on top.
- [x] There needs to be a concept on how this is structured on the dev side
- [x] ~Define how this relates to the grid system~
  - It doesn't
- [x] Update the implementation proposal
- [x] Documented the density concept
- [x] Create follow-up dev & UX ticket
  - [x] tickets for dev implementation #368 

**Approval**

- See new density prop in [RadioButtonGroup](https://storybook.onyx.schwarz/?path=/docs/components-onyxradiobuttongroup--docs)
-  See new density prop in [RadioButton](https://storybook.onyx.schwarz/?path=/docs/support-onyxradiobutton--docs)
- [Wiki entry for Density](https://github.com/SchwarzIT/onyx/wiki/Coding-Guidelines#density)
- [Density System Documentation](https://onyx.schwarz/development/density.html)

- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Resources:
- https://web.dev/articles/accessible-tap-targets?hl=en
- https://developer.mozilla.org/en-US/docs/Web/CSS/@media/pointer

**Comment by larsrickert** [comment]
I don't think we can implement the density using CSS classes. I'd prefer properties because they are better usable and I can imagine that it is component specific what styles need to be changed for a specific density. For example, a button might have a different padding on the main element but a checkbox has a different size of the nested input/box element.

**Comment by BoppLi** [comment]
> I don't think we should implement the density using CSS classes. I'd prefer properties because they are better documented and I can imagine that it is component specific what styles need to be changed for a specific density. For example, a button might have a different padding on the main element but a checkbox has a different size of the nested input/box element.

but shouldn't there still be a way to set e.g. "cozy" globally once for the "glove" use-case? if we only have props, _every_ component would need to have `density="cozy"` set on it which sounds a bit unconvenient in terms of DX?

**Comment by larsrickert** [comment]
> but shouldn't there still be a way to set a default for an application, e.g. set "cozy" globally once for the "glove" use-case? if we only have props, _every_ component would need to have `density="cozy"` set on it which sounds a bit unconvenient in terms of DX?

We have #328 where we can add a global option to define the default density so the user doesn't have to add it to every component :)

**Comment by JoCa96** [comment]
From @jannick-ux : https://medium.com/google-design/using-material-density-on-the-web-59d85f1918f0

**Comment by larsrickert** [comment]
@JoCa96 I'd prefer to move the `styles/density.ts` file to the types folder so the `styles` folder only contains CSS/SCSS
