### ISSUE TITLE
Concept flyout

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#256]
### Create flyout
- [ ] all needed variation
- [ ] all necessary states
- [ ] dark mode
- [ ] density

### Functions
- [ ] Can be used in Figma and is available as a component
- [ ] Shows all states

### Figma
- [ ] dev handover
- [ ] ux component

### documentation
- [ ] keyboard support
- [ ] property description
- [ ] textual documentation
- [ ] component grouping

**Comment by mj-hof** [comment]
![Image](https://github.com/SchwarzIT/onyx/assets/152193246/7621c7c8-e966-479c-8bd9-74dace8574f1)

**Comment by larsrickert** [comment]
Approved :)
