### ISSUE TITLE
Implement Support Component Naming Convention + Exposure

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#293]
Conclusion: the implementation task of this ticket is:

- [x] Restructure components in folders
- [x] Restructure storybook 
  - update links in the docs landing page
  - clarify structure with Jannick
- [x] Export all components
- ~~Look into bundling imports~~

### Discussion meeting notes

- Which support components should we export?
  - we could export everything except in rare situations: e.g. "male avatar", "female avatar"
  - OUT OF SCOPE (future optimization) ~we could export different namespaces (e.g. sit-onyx/support) instead of placing all in the index.ts so it does not get too cluttered~
  - support components have a standard info in the JSDoc that they are JUST support components
  - consequence: we have to keep even the API of our internal components steady, might create more major versions in the long run. alternatively: inform users that support components might change their API without major versions.
- we want to group different kinds of support components:
- Following components will be moved up to their "parent" components in storybook:
  - OnyxNavItem
  - OnyxNavSeparator
  - OnyxTimer
  - OnyxNavAppArea
  - OnyxListItem
  - OnyxVisuallyHidden
  - OnyxFlyoutMenu
- "Internal"
  - OnyxIntCheckbox
  - OnyxIntRadioButton
  - OnyxIntMiniSearch
  - OnyxIntSelectInput
  - OnyxIntSelectOption
- Should they be prefixed with `Onyx`? Or an alternative prefix, e.g. `Internal`, `Support`, ...?
- Should support components be part of the `components` folder or be moved to another one?
  - Info: some like MiniSearch are already included in folders of "official" components
  - if a component is tightly coupled, it should be in the folder of the "parent"
  - we won't create a new folder for the internal components
  - In Storybook, we can bundle components into folders, e.g. all NavBar components
- IF we would export all components, should we consider bundling our imports inside our components like that to further leverage the index file?:
  - we can do that, IF storybook does not break and IF it won't cause recursive dependencies.
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/5202f833-d3da-4374-8a7a-1bf98f018ca2)

### Details

File structure / naming conventions for distinguishing "private" components:
The folder of a support component should not have the "Onyx" in the name. but if we want to use another keyword, we have still to decide.

Also Discuss if we want to export support components
Do we want to technically export support components like OnyxCheckbox so they can be used for custom content / edge cases by the projects if the main component (e.g. checkbox group in this example) is not sufficient? 

Current support components are:

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/83890d38-080c-4995-892a-20fecaf35a26)
Also (not listed in storybook): OnyxListItem

**Comment by larsrickert** [comment]
New Storybook sidebar structured as discussed with Jannick:

# Component groups

## Buttons

- Button
- Icon button

## Form

- Checkbox group
- Input
- Radio button group
- Select
- Switch
- Textarea

## Basic

- Avatar / Avatar stack
- Badge
- Tag
- Headline
- Icon

## Data

- Table
- Empty
- Pagination

## Feedback

- Toast
- Dialog / Modal
- Tooltip

## Navigation

- Nav bar
- Link

### Modules

- Color scheme dialog
- Flyout menu
- Nav button
- Nav item
- Nav separator
- Timer
- User menu

## Layout

- App layout
- Page layout

## Support

- Loading indicator
- Skeleton
- Checkbox
- Form element
- Info tooltip
- Mini search
- Mobile nav button
- Nav app area
- Radio button
- SelectInput
- SelectOption
- Visually hidden

GridPlayground will be removed from Storybook and placed inside the docs
