### ISSUE TITLE
Implement new component feature in documentation

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#294]
### Depends on

- [x] Depends on [#237](https://github.com/SchwarzIT/onyx/issues/237)

### Why?

Due to a top level decision, our components shouldn't be structured into different sets on our documentation start page, so we have to change the visualization of this feature.

### Design

[Figma Link](https://www.figma.com/file/yPj9gRAHzqY1NPky9k8Voz/onyx-docu?type=design&node-id=0%3A1&mode=design&t=4PE7fmUc97CxGw9a-1)

### Acceptance criteria

- [x]  Remove the tab layout
- Initially, 12 component tiles are shown
  - [x] 4 Tiles per row in the default layout. Make it adjust responsively
  - [x] Try out how 12 tiles "feel" on a mobile device. Reduce number of initial tiles for mobile if needed.
- [x] With a "more" option, the user can switch between showing the 12 or all component tiles
- [x] Order the tiles on the implementation status: `Implemented` first, then `In Progress`, then `Planned`
- [x] Update the intro text above the tiles
- [x] Provide a legend for that status badges

### Definition of Done

- [x] updated version + documentation is deployed
- [x] Set task to `In review`

**Review**

- [Documentation link](https://onyx.schwarz)
- [x] approved by designer @mj-hof 
- [x] approved by dev @BoppLi 

### Implementation details

- stay close to the current implementation
- the relevant component for the tiles is `apps/docs/src/.vitepress/components/ComponentCard.vue`
- the relevant components for the layout are `apps/docs/src/.vitepress/components/OnyxRoadmap.vue` and `apps/docs/src/.vitepress/components/ComponentGrid.vue`

**Comment by mj-hof** [comment]
Please also change or add some other status chips, i.e. like planned, implemented, work in progress, partly implemented

**Comment by BoppLi** [comment]
Note from the Daily:

- [ ] use plain button instead of the OnyxLink for `show less` / `show more`
