### ISSUE TITLE
Remove readonly state 

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#339]
### Why?

The HTML standard only supports readonly for text inputs and textareas, so we should remove any readonly states from other components.

### Acceptance criteria

- in Figma, all readonly designs/states are removed from all components except the input and textarea

### Definition of Done

- [ ] covered by component tests
- [ ] screenshot tests are updated
- [ ] follow up tickets were created if necessary
- [ ] updated version + documentation is deployed
- [ ] Storybook can show the feature
- [ ] Set task to `In review`

**Review**

- _add link to deployed storybook_
- _add link to deployed docs_
- [ ] approved by designer @jannick-ux
- [ ] approved by dev _add dev tag_

**Comment by mj-hof** [comment]
Re-refine ticket again for removing readonly
