### ISSUE TITLE
Implement truncation

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#364]
**Acceptance criteria**
- [x] Storybook should offer a possibility to set the width to demonstrate the truncation

**OnyxButton**
- [x] There is no line break with buttons. They always are truncated with longer labels.

**OnyxCheckbox**
- [x] The label has no max width by default. However it can be set manually.
- [x] The developer and designer can decide if he wants truncation or line break, with a property
- [x] The height of a checkbox with multiline should grow (so there is still the regular distance to the next/previous checkbox)

**OnyxRadioButton**
- [x] The label has no max width by default. However it can be set manually.
- [x] The developer and designer can decide if he wants truncation or line break, with a property
- [x] The height of a radio with multiline should grow (so there is still the regular distance to the next/previous radio)

**OnyxSwitch**
- [x] The label has no max width by default. However it can be set manually.
- [x] The developer and designer can decide if he wants truncation or line break, with a property
- [x] The height of the switch with multiline should grow

**Design**

- [Button](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=723-11417&mode=dev)
- [Checkbox](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=621-13555&mode=dev)
- [Radio button](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=626-15741&mode=dev)
- [Switch](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=719-10053&mode=dev)

**Out of scope**
- Tooltip for the truncation

**Definition of Done**

 - [x] covered by component tests
 - [x] screenshot tests are updated
 - [x] updated version + documentation is deployed
 - [x] Storybook can show the feature
 - [x] Set task to In Approval

**Review**

- [Button Storybook](https://storybook.onyx.schwarz/?path=/story/components-onyxbutton--with-truncation)
- [Checkbox group Storybook](https://storybook.onyx.schwarz/?path=/story/components-onyxcheckboxgroup--with-truncation)
- [Radio button group Storybook](https://storybook.onyx.schwarz/?path=/story/components-onyxradiobuttongroup--with-truncation)
- [Switch Storybook](https://storybook.onyx.schwarz/?path=/story/components-onyxswitch--with-truncation)
- [x] approved by designer @jannick-ux 
- [x] approved by dev @MajaZarkova 

**Implementation details**
- Default doesn't have a max width

**Comment by mj-hof** [comment]
Whats with the radio button?

**Comment by jannick-ux** [comment]
yes you are right. This was an old definition, that is outdated. Sorry for the confusion.

**Comment by larsrickert** [comment]
> yes you are right. This was an old definition, that is outdated. Sorry for the confusion.

Can you then also adjust this in Figma?
