### ISSUE TITLE
Implement density

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#368]
### Depends on:

- [x] #246 

### Acceptance criteria

- [x] For all existing component, that support density:
  - [x] Extended component properties with `DensityProp`
  - [x] Implemented all three densities types
- [x] Add feature to Alpha-Test-App to toggle density for the whole page
- [x] Updated AC in the [Dev Reference Ticket](https://github.com/orgs/SchwarzIT/projects/5/views/7?filterQuery=refer&pane=issue&itemId=49798142) to include density as a new baseline requirement

### Design

- [Figma Button](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=896%3A5709&mode=dev)
- [Figma Checkbox](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=511%3A199&mode=dev)
- [Figma RadioGroup](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=626%3A15811&mode=dev)
- [Figma Switch](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=711%3A12776&mode=dev)

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In final approval`

**Review**
- [Storybook Button](https://storybook.onyx.schwarz/?path=/docs/components-onyxbutton--docs)
- [Storybook Checkbox Group](https://storybook.onyx.schwarz/?path=/docs/components-onyxcheckboxgroup--docs)
- [Storybook Icon Button](https://storybook.onyx.schwarz/?path=/docs/components-onyxiconbutton--docs)
- [Storybook Input](https://storybook.onyx.schwarz/?path=/docs/components-onyxinput--docs)
- [Storybook RadioButton Group](https://storybook.onyx.schwarz/?path=/docs/components-onyxradiobuttongroup--docs)
- [Storybook Swith](https://storybook.onyx.schwarz/?path=/docs/components-onyxswitch--docs)
- [x] approved by designer @mj-hof 
- [x] approved by dev @larsrickert 
  

### Implementation details

- Refer to https://github.com/SchwarzIT/onyx/wiki/Coding-Guidelines#implementing
- See prototype implementation in https://github.com/SchwarzIT/onyx/blob/main/packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue

**Comment by mj-hof** [comment]
Whats with the radio button?
