### ISSUE TITLE
Implement OnyxIconButton

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#386]
### Depends on

- [x] #190

### Why?

- In addition to the OnyxButton we want to implement the OnyxIconButton as a standalone button.
- It's different enough to be its own component

### Design

[Figma link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=836-6659&mode=design)

### Acceptance criteria

- Supports mode:
  - [x] primary
  - [x] secondary
  - [x] danger
- States:
  - [x] default
  - [x] disabled
  - [x] loading
- Focus:
  - [x] none
  - [x] hover
  - [x] focus-visible
- [ ] ~For the LayoutDemoPage in the alpha-test-app: 
        replace the OnyxButton inside the "flotingbutton" component with `OnyxIconButton`~

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In review`

**Review**

- [Storybook](https://storybook.onyx.schwarz/?path=/docs/components-onyxiconbutton--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

- must always require label for ARIA purposes

#### Reference implementations

- [CoreUI](https://core-ui.schwarz/components/scu-icon-button)

#### Applicable ARIA Pattern

- [Button](https://www.w3.org/WAI/ARIA/apg/patterns/button/)

**Comment by JoCa96** [comment]
> For the LayoutDemoPage in the alpha-test-app: 
>   - replace the OnyxButton inside the "flotingbutton" component with `OnyxIconButton`

Removed this AC, as the button not intended to be used here from a design perspective

**Comment by jannick-ux** [comment]
The icon size is restricted to 24px. It cannot be larger or smaller. 
Also please use the icon "trash" as default icon.
