### ISSUE TITLE
Implement OnyxLoadingIndicator

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#390]
### Why?

We want to offer a loading indicator component that can be used to indicator that some async / long-running action is currently in progress / loading.

### Design

- [circle](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=616-4903&mode=dev)
- [dots](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=662-6835&mode=dev)

### Acceptance criteria

- an animated loading indicator can be displayed
- the following types are supported:
  - [x] circle (spinning animation)
  - [x] dots (2 bigger dots, 1 smaller dot, and they are animated)

### Definition of Done

- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Review**

- [Storybook link](https://storybook.onyx.schwarz/?path=/docs/components-onyxloadingindicator--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96 

### Implementation details

- the indicator should use `currentColor` as color so it aligns with the text color
- prefer CSS animation over JavaScript if possible

```ts
export type OnyxLoadingIndicatorProps = {
  type: "circle" | "dots";
};

const props = withDefaults(defineProps<OnyxLoadingIndicatorProps>(), {
  type: "circle",
});
```

**Comment by JoCa96** [comment]
Maybe we can just use special svg and use the OnyxIcon: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate

**Comment by jannick-ux** [comment]
Please change the anomation from the dot-variant. Currently the majority of the dot-loading-indicator is bright and only one dot gets darker at the time. Please do the opposite way, so that the majority is darker and only one dot is lighter.

**Comment by JoCa96** [comment]
@larsrickert Please change the keyframe timings from 0%,30%,60% to 0%,33%,66%, so the animation is more symmetrical
