### ISSUE TITLE
Research color contrast for themes

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#410]
- Regarding our accessibility topic, check the color contrast especially for the Digits theme (maybe Kaufland…)
- [ ] table hover effects in dark mode barely visible
- [x] #859

### Teams chat to this topic
https://teams.microsoft.com/l/message/19:KGEIFTqojUuOMMggXfOhvc772DhwrQWRJNMqrnvL6ak1@thread.tacv2/1707918850979?tenantId=d04f4717-5a6e-4b98-b3f9-6918e0385f4c&groupId=969ca3b3-9c78-411f-8629-eb770bbfdc7b&parentMessageId=1707918850979&teamName=onyx&channelName=General&createdTime=1707918850979

**Comment by ChristianBusshoff** [comment]
color-contrast Rule got disabled for the Projekt in 
packages/sit-onyx/src/playwright/a11y.ts
Should be removed.
