### ISSUE TITLE
Storybook: Optimize code preview

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#414]
Task: make a utility for our storybook code demos:
The goal is to separate the code example between "script" and "template" sections

Example:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/2b9bee34-80ee-41f5-85a9-432fa009c16b)

**Comment by larsrickert** [comment]
https://github.com/storybookjs/storybook/discussions/26691
