### ISSUE TITLE
Create readme files

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#42]
1. [x] README/Getting started Info (Lars)
2. [x] Contribution Philosophy (Linda)
   - -> https://github.com/SchwarzIT/onyx/pull/137
3. [x] Wiki content (Tech Vision) (Linda)
   - -> https://github.com/SchwarzIT/onyx/wiki/Technical-Vision-&-Guidelines
3. [x] Wiki content (DOD / DOR) (Linda) 
   - -> https://github.com/SchwarzIT/onyx/wiki/Component-Quality-Layers 
   - -> https://github.com/SchwarzIT/onyx/wiki/Definition-of-Ready-&--Done

**Comment by BoppLi** [comment]
Original Notes:

- Getting started, Contribution philosophy. 
- Vorlage von OSS prüfen. 
- -> Contributions.md muss enthalten: 
  - minimal dependencies (deps) and devdeps 
  - every dep must be well justified  
    - checklist of things to consider 
  - Branch names are prefixed by their CC keyword, e.g. "chore"

**Comment by BoppLi** [comment]
> [10:53] Patrick Hahn
> Guten Morgen, es gibt den Code of Conduct, auf den man verweisen kann, aber ansonsten nichts bestimmtes. Es wäre natürlich für Contributer sehr hilfreich, wenn da drinsteht wie man von Zero zu Pull Request kommt, und wie man den dann gemerged bekommt, was man dabei alles beachten muss. Das ist natürlich von Projekt zu Projekt unterschiedlich, deswegen geben wir da nichts direkt vor.
>  
> https://github.com/SchwarzIT/.github/blob/main/CODE_OF_CONDUCT.md
