### ISSUE TITLE
Fix zoom in/out behavior on OnyxSwitch

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#503]
The issue is reproducible when you zoom in or out with your keyboard, the gap between the white circle and the border of the component is changing. It only happens for certain zoom levels.

Screenshots for comaparation:

![Image](https://github.com/SchwarzIT/onyx/assets/60856270/900e8bb1-a89a-47bf-801b-e1ea0735e47f)

![Image](https://github.com/SchwarzIT/onyx/assets/60856270/7483c3a3-44a2-4c17-869b-fe86fc6f13bc)

Reproduction: Zoom size 175% with Chrome
https://playground.onyx.schwarz/#eNp9Uk1v2zAM/SuETh1QJYftlLkFtqGH7bAO6y4DBAyKTDtqZcmQKDdBkP8+Su6HC7S9GCL5SL/3yKP4Mo6rKaPYiCaZaEcCp31/oQQlJSAh5fFSeTuMIRIc4dof9jf3lswOTtDFMIASyZIMnFfi8wIZsXuG8B9qVXkTfCKYtMsIFwV0poQSH7jWrGcC/DsOCIfRaUKOAJrx8m/IYLQHbC0B7RBMaBGCr2+HHYH2LfPFOWEn5OEpO0qww4irZl108KiFAqe36FjqHLLcgWc6WckVB2JhDWvua9YLPhwmOrjy3Ib2AMcytwueZKcH6w4blhfPZPVELvJFJMBWm7s+huxbaYIL8QW6ZuRWJ+TPE46sJ2zn9rd6CPckbXFXeswUtZOlyycsfadq7wNpcc7LZWRn+9VtCp53XyUoYcIwWofxeiTLk5TYzOJKTTsX7n/UXDHm/DFvdmjuXsnfJj6IDT9+8R4wTmzlU4107JHm8tXNT6a+KPISsmP0O8XfmILLheMM+8ouMe0FrrL9Xm/R+v5PutoXLx5F1c0y8lTx9Ty/vSP9me7H1afax46yi/8mjGUmG1hOI5E4/QcEhyJB

### Approval

- [Storybook](https://storybook.onyx.schwarz/?path=/docs/components-onyxswitch--docs)
- [x] Approval from @jannick-ux 
- [x] Approval from @larsrickert

**Comment by BoppLi** [comment]
Noteworthy: does not happen on the macbook screen, but on an external monitor with resolution 1920x1080

**Comment by BoppLi** [comment]
The span with the background color itself is the thing that causes trouble.
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/a41edb1f-cea4-4a80-bee2-fb8debbf2eef)

**Comment by BoppLi** [comment]
The problem exists only with even pixel values of the height.
Default implementation has 20px:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/78a7e09b-7541-4e5b-8666-246342fdc052)

The problem is fixed when using un-even numbers.
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/2382543f-0527-4add-97ec-2de1cde22197)

**Comment by BoppLi** [comment]
The origin of our issue: The browser changes "1px" to 0.8px which makes it impossible to center an even sized content properly.

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/712e54d9-8282-45a9-9486-9f381958e6aa)

see also https://stackoverflow.com/a/44273608

**Comment by BoppLi** [comment]
Notes from the daily:
- [ ] remove border
- [ ] for invalid state, use outline
