### ISSUE TITLE
Implement tooltip

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#567]
### Open questions

- [x] Can we remove the Figma requirement to truncate the tooltip text after 3 rows?: Yes, don't truncate after 3 lines

### Why?

Tooltips in ui design and web development offer contextual information or additional details to a parent element.

### Design

[Figma link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=957-897&mode=dev)

### Acceptance criteria

- a tooltip can be shown with one of the following colors
  - [x] default
  - [x] danger
- [x] an optional icon can be shown on the left side of the label
- [x] the text is truncated with mutliline
- [x] a the wedge is displayed and can be positioned manually via a property
- the tooltip can be triggered via:
    - [x] hover
    - [x] click
    - [x] manually set boolean

#### Out of scope:

- #730

### Definition of Done

- [x] example usage added to alpha-test-app
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Review**

- [Storybook link](https://storybook.onyx.schwarz/?path=/docs/components-onyxtooltip--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96 

### Implementation details

- Use type `OnyxColor` for color property
- Use class `onyx-truncation-multiline` for the truncation
- Use z-index `var(--onyx-z-index-flyout)`

#### Applicable ARIA Pattern

[Tooltip pattern](https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/)

**Comment by BoppLi** [comment]
Question: should the tooltip be auto-applied to all components where a "title" property is set for consistency?

**Comment by larsrickert** [comment]
> Question: should the tooltip be auto-applied to all components where a "title" property is set for consistency?

We currently have no components with a title property, right?

**Comment by BoppLi** [comment]
> > Question: should the tooltip be auto-applied to all components where a "title" property is set for consistency?
> 
> We currently don't have any components with a title property, right?

As Jonathan said, title can be set on every component and it will trigger the auto-tooltip of the browser on hover. If we set it explicitly as new property I think it would disable the browser auto-tooltip so we could place our own.. maybe we can discuss this in the next dev exchange :)

Btw, is the OnyxTooltip supposed to trigger on hover in the future?

**Comment by larsrickert** [comment]
>  If we set it explicitly as new property I think it would disable the browser auto-tooltip so we could place our own

I'd say you can just wrap the component inside the OnyxTooltip and not set the title then so its more flexible and we don't have to implement it for every component.

> Btw, is the OnyxTooltip supposed to trigger on hover in the future?

Yes you can decide between hover and click, I am working on this

**Comment by BoppLi** [comment]
Notes from the call with Jannick: In the future, we should use our internal OnyxTooltip for the title use case, but for now, we can stick with the title property.

**Comment by jannick-ux** [comment]
looks very nice. But 2 questions here:

Ist the icon optional or mandatory?
Have you considered the defined shadow?

**Comment by larsrickert** [comment]
> Ist the icon optional or mandatory?
Its optional, I just added it per default to the example. Should I add an example without icon?

> Have you considered the defined shadow?
Yes there is no shadow in dark mode. I also added a new `onyx-box-shadow` variable/token that we can also use in other components (e.g. the flyout/listbox) so we don't have to copy it everywhere.

**Comment by jannick-ux** [comment]
Okay, so I approved this component. 
Although we should have a little technical talk about the usage of shadows. I want to understand how the implementation and flexibility works in detail here. 
But no hurry on that.

Good work!

**Comment by larsrickert** [comment]
Add example without icon

**Comment by larsrickert** [comment]
Check how click is working on mobile
