### ISSUE TITLE
Implement OnyxBadge

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#568]
#564 

### Open Questions/To-dos

- [x] _Should Aria pattern be added and which one? -> No_

### Why?

_Info badges in UI design serve as valuable tools for conveying various types of information to users._

### Design

[Figma Link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1009%3A321975&mode=dev)

### Acceptance criteria

- Supports mode:
  - [x] primary
  - [x] secondary
  - [x] danger
  - [x] warning
  - [x] success
  - [x] info
- Supports type:
  - [x] text
  - [x] number
  - [x] icon
- States:
  - [x] truncated
- [x] Add feature to Alpha-Test-App
- [x] Add badge to OnyxSelect and remove temporary styles

#### Out of scope

- dot

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Review**

- [StoryBook Link](https://storybook.onyx.schwarz/?path=/docs/components-onyxbadge--docs)
- [OnyxBadge inside OnyxSelect](https://storybook.onyx.schwarz/?path=/story/components-onyxselect--filled-multi-select-preview)
- [x] approved by designer @jannick-ux
- [x] approved by dev @BoppLi 

### Implementation details

- The badge should have the same design like in FIgma

#### Reference implementations

- [CoreUI](https://core-ui.schwarz/components/scu-badge)

**Comment by jannick-ux** [comment]
Regarding my Review: I think we should stick with the properties that are given in Figma. "type" for primary, secondary, etc. and "mode" for text, number, icon etc.

I am not completely happy with the experience and usage of properties (e.g. to switch its appearance from "text" to "icon" only by setting one). So please change the property behavior under the hood to match with Figma. 
From a visual perspective, the component looks fine!

**Comment by jannick-ux** [comment]
One addition: I canged the icon size of the default-density. It is now 16x16 instead of 24x24

**Comment by larsrickert** [comment]
> "type" for primary, secondary, etc

We have #829, imho we should rename properties that change the color to `color`

> "mode" for text, number, icon etc.

This is technically not possible because (1) if an icon is used it must be provided as property so we can change the padding accordingly but (2) when text/number is used it is passed as slot which must have the name `default`. So doing this with only one property is technically not possible and imho not intended
