### ISSUE TITLE
Implement input/textarea invalid state

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#570]
### Depends on

- #189
- #567
- #565 
- Blocked by #574  

### Why?

The input, textarea ~and select~ should be able to show an invalid state to show the user that the entered value is invalid and he has to perform further actions.

### Design

- [Figma - input](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1475-259920&mode=dev)
- [Figma - textarea](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1259-76009&m=dev)
- ~[Figma - select](https://www.figma.com/design/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1504-31388&m=dev)~

### Acceptance criteria

- the input is shown invalid with a default translated error message if the validation for one of the following properties fails:
  - [x] required
  - [x] minlength
  - [x] maxlength
  - [x] pattern
- For each error type (min/max length, pattern missmatch..., 
  - [x] a short text summary is displayed below the input 
  - [x] with a more detailed text in the tooltip).
- [x] a custom error message can be passed
- [x] the `TestInput` component is replaced with the `OnyxInput` inside the alpha demo app.
  - [ ] ~The TestInput is moved to the alpha test app for number inputs.~
- Implement translated error message like in OnyxInput for all other existing form components that we have.
  - [x] OnyxTextarea
  - [ ] ~OnyxSelect~ -> #1302
- [x] inside the alpha-test-app, inside the FormDemoView, include all modified form components from this ticket as examples
- [x] verify: the translation for the preview texts don't need data object? (e.g. value, n, max, ..) -> then shorten the useCustomValidity errorMessages.
- [x] for customError: support `{longError string, shortError: string}` aswell as the current `string`

### Definition of Done

- [x] example usage added to alpha-test-app
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
  - #1302 
  - #1312
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Review**

- [Storybook - Input required example](https://storybook.onyx.schwarz/?path=/story/components-input--required)
- [Storybook - Input minlength example](https://storybook.onyx.schwarz/?path=/story/components-input--maxlength)
- [Storybook - Input customError example](https://storybook.onyx.schwarz/?path=/story/components-input--custom-error)
- [Storybook - Textarea customError example](https://storybook.onyx.schwarz/?path=/story/components-textarea--custom-error)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

- use `:invalid` pseudo CSS-selector

**Comment by BoppLi** [comment]
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/711b0af0-c6c0-4837-b708-99c619a081ce)
