### ISSUE TITLE
[Bug]: Using TS path mappings breaks types in Storybook

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#589]
### Version

latest

### Description

Storybook seems unable to resolve TS path mappings when constructing `argTypes`:
This breaks all props as seen here:

Not Working:
```ts
import type { DensityProp } from "@/styles/density";
```

![Image](https://github.com/SchwarzIT/onyx/assets/18483883/cb31712b-8fc7-44fc-90c4-2b739b532a9e)

Working:
```ts
import type { DensityProp } from "../../styles/density";
```

![Image](https://github.com/SchwarzIT/onyx/assets/18483883/4763d4ad-0848-4254-8ee0-da9f08935642)

**Comment by larsrickert** [comment]
This is a know limitation of vue-component-meta (Volar): https://storybook.js.org/docs/get-started/vue3-vite#limitations

**Comment by larsrickert** [comment]
I will close this because we removed the `@/` type alias
