### ISSUE TITLE
Create DNS alias for showcase

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#60]
Order the following domains.

| Domain                     | Environment | Application |
| -------------------------- | ----------- | ----------- |
| onyx.schwarz               | prod        | Docs        |
| storybook.onyx.schwarz     | prod        | Storybook   |
| onyx-dev.schwarz           | dev         | Docs        |
| storybook.onyx-dev.schwarz | dev         | Storybook   |

**Comment by larsrickert** [comment]
Currently waiting for DNS team to create the domains and SSL certificates

**Comment by JoCa96** [comment]
New ticket: NSR4306239
