### ISSUE TITLE
Implement browser alignment to onyx dark/light mode

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#618]
### Why?

Currently we are using a `.dark` CSS class for the dark mode which has 2 downsides:

1. It does not work out of the box / the project explicitly has to implement it
2. Even if the class is set, browsers default components like scrollbars etc. will still be in light

We should use media queries and the `color-schema: light` or `color-schema: dark` CSS property

### Acceptance criteria

- [ ] ~the light/dark CSS variables use a media query for the user preferred color schema instead of classes~
  - [x] the `color-schema` should also be set to dark or light based on that
- [ ] ~Our `storybook-utils` and `vitepress-theme` are checked and updated accordingly~
- [x] A "Theming" page in our docs is added that explains the usage of light/dark mode
  - [x] can reference [`useDark`](https://vueuse.org/core/useDark/#usedark) from `vueuse` for switching
- [ ] ~The [Playground](https://playground.onyx.schwarz) works with the new implementation~
- [ ] ~The `chartjs-plugin` package is updated accordingly~
- [ ] ~update figma variable import pipeline~

### Definition of Done

- [ ] ~covered by component tests~
- [ ] ~screenshot tests are updated~
- [ ] ~follow-up tickets were created if necessary~
- [ ] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- ~Storybook~ -> only visible in alpha test app
- [x] approved by designer @jannick-ux
- [ ] approved by dev 

### Implementation details

- localStorage key should have a default value but can be changed

#### Reference implementations

- [`useDark`](https://vueuse.org/core/useDark/#usedark) from `vueuse`

**Comment by BoppLi** [comment]
Authors Note: After looking into it with Lars, most of the ticket can not be solved. 
The reason is that the [media query for scheme selection](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme#styling_based_on_color_schemes) only respects the system settings.

So the only things that are implemented in this ticket now are:
- Include the color-scheme in the dark/light classes / theme setup
- Add a button to toggle dark/light in the alpha demo app

**Comment by larsrickert** [comment]
@BoppLi Can you remove the manual setting of the color scheme in `packages/storybook-utils/src/preview.ts`?
 
![image](https://github.com/SchwarzIT/onyx/assets/67898185/e26ad0e4-ecf5-4424-9759-fc7c26fdd9db)

**Comment by BoppLi** [comment]
as discussed, won't be changed as the storybook util has no access to the root.scss's scheme setting :)
