### ISSUE TITLE
Storybook: Implement A11y addon

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#641]
### Why?

We want to emphasize our focus on accessibility.
By adding the [addon-a11y](https://storybook.js.org/addons/@storybook/addon-a11y) add-on to our Storybook, we are able to show our commitment to accessibility and the quality of our components. 

### Acceptance criteria

- [x] The Accessibility tab of the add-on is available in our Storybook Stories
- [x] If possible, share the axe configuration (not the ignore rules)

### Definition of Done

- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/buttons-iconbutton--primary), the ticket is about the accessibility tab right next to 'Controls' and 'Actions'.
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96 

### Implementation details

- Follow the instructions on https://storybook.js.org/addons/@storybook/addon-a11y

#### Reference implementations

- [Trinity](https://ods-lidl-web-vuejs-storybook.apps.01.cf.eu01.stackit.cloud/?path=/story/ods-addonbadge--default)

**Comment by larsrickert** [comment]
@MajaZarkova Do you know which rules the addon applies/checks by default? Since we decided to aim for AA, we should ensure that all rules for AA are also included in the Storybook addon :)

**Comment by MajaZarkova** [comment]
I don't, but I can investigate

**Comment by MajaZarkova** [comment]
@larsrickert , I found the list with the rules -> https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

**Comment by larsrickert** [comment]
> [@larsrickert](https://github.com/larsrickert) , I found the list with the rules -> https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md

These are just all available rules, right? We should check which of them are actually checked by the Storybook addon. E.g. it might only check a few of them by default and we might need to configure it to check more. But I am not sure 🤔
