### ISSUE TITLE
Fix checkbox optional/required marker not shown when truncated

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#698]
The optional/required marker is not shown when truncated with ellipsis

![Image](https://github.com/SchwarzIT/onyx/assets/67898185/0ee123f5-6c9a-4312-abb7-1b0815c1058b)

### Definition of Done

- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- ["optional" truncation example](https://onyx-storybook-prod.apps.01.cf.eu01.stackit.cloud/?path=/story/components-onyxcheckboxgroup--with-truncation&globals=requiredMode:optional)
- ["required" truncation example](https://onyx-storybook-prod.apps.01.cf.eu01.stackit.cloud/?path=/story/components-onyxcheckboxgroup--with-truncation)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96

**Comment by BoppLi** [comment]
> > [12:58 PM] Linda Bopp
> > Optional label behavior and truncation
> > ux I have a question about the intended behavior of the "optional" label in combination with truncation and multiline mode.
> > Currently it behaves like this (https://github.com/SchwarzIT/onyx/issues/698) (see screenshot in ticket)
> >  
> > in the first example, should "optional" be fixed to the right and the "Very long label" will be even shorter until the ... happens?
> > in the last example, can it stay as it is? 
> > in the following example, should the optional labels be right-aligned on the same position?
> > 
> > ![Image](https://github.com/SchwarzIT/onyx/assets/151019977/16775563-7150-411b-b6a0-10860065df67)
> > 
> 
> ----
> 
> [1:04 PM] Jannick Keller
> To the first question:
> Yes the optional-label has a higher priority than the checkbox-label. Therefore the optional-label will be fully readable on the right and the checkbox-label will use the rest of the available space (pending on the max width) before it gets ...truncated.
>  
> The last example of the top image is correct.
>  
> To the second image: the optional-labels don't have to be aligned to the same vertical position.
>  like 1
