### ISSUE TITLE
Implement Playground / bug reproduction template

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#704]
### Why?

We want to have a way where users can (1) easily try out onyx and (2) be able to use it as reproduction template for e.g. bug reports where users can write reproduction code and share it in the bug report.

### Acceptance criteria

- [x] A playground editor is created
- [x] The edited code can be copied / shared so other users can easily view it
- [x] The GitHub bug report template is updated to require a reproduction code example
- [x] The onyx version can be changed so the user can check when the issue was introduced and if it still exists in the latest version

### Definition of Done

- [x] updated version + documentation is deployed
- [x] Set task to `In Approval`

**Approval**

- [Playground](https://playground.onyx.schwarz)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96 

### Implementation details

- [Vue.js Playground](https://play.vuejs.org)
- [Element Plus Playground](https://element-plus.run)

**Comment by JoCa96** [comment]
@larsrickert Only three minor issues:
Ideally the console is kept clean:

1. There are a lot of warnings in the console
2. There is an error when switching the color-schema in firefox:
<img width="1724" alt="Screenshot 2024-04-04 at 18 40 18" src="https://github.com/SchwarzIT/onyx/assets/18483883/90edcf20-0366-446e-8145-47e76aa2b957">
3. The Playground doesn't seem to consider my preferred color-scheme.

**Comment by larsrickert** [comment]
@JoCa96 
> 1. There are a lot of warnings in the console

The warnings come from the editor itself so we can not prevent them at the moment. I fixed the errors tho

> 2. There is an error when switching the color-schema in firefox

Fixed

> 3. The Playground doesn't seem to consider my preferred color-scheme.

Fixed
