### ISSUE TITLE
Implement auto alignment/position for OnyxTooltip

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#730]
Relates/Depends on

- [x] #574
- [ ] Regard WaWi implementation for this issue 

### Why?

We want to automatically align the OnyxTooltip based on its position on the screen to improve visibility.

### Acceptance criteria

- [x] tooltip is position top if more screen space is available above than below
- [x] tooltip is position bottom if more screen space is available below than above
- [x] wedge is aligned left if tooltip is too close the the left border of the viewport
- [x] wedge is aligned right if tooltip is too close the the right border of the viewport
- [x] on all `.stories.ts` which have decorators, remove the padding if it was only needed ot show the tooltip on top/centered

### Definition of Done

- [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- _add link to deployed storybook_
- _add link to deployed docs_
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

_add details if necessary, e.g.,_

- _API proposal_
- _relevant web APIs_
- _learnings from other implementations_
- _code snippets_

#### Reference implementations

- _add links to other framework and WaWi_

#### Applicable ARIA Pattern

_add link if applicable_

**Comment by mj-hof** [comment]
Relates to #763 
File reference: ui/components/src/components/WuxPopover/WuxPopover.core.ts

**Comment by BoppLi** [comment]
Other reference implementation: CoreUI

**Comment by oemueller** [comment]
checkout anchor positioning (can be polyfilled):
https://frontendmasters.com/blog/what-you-need-to-know-about-modern-css-spring-2024-edition/#anchor-positioning
