### ISSUE TITLE
Implement multiselect for OnyxListbox

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#732]
### Depends on

- #564

### Why?

The OnyxListbox should also support multiselect to select multiple values.

### Design

[Figma link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1130-19227&mode=dev)

[Flyout design with multi example](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1009%3A320042&mode=dev)

### Acceptance criteria

- [x] multiple values can be selected
- [x] the ARIA pattern linked below is implemented (aria attributes, keyboard support)
- [x] an optional "Select all" can be shown
- [x] options can be set to disabled
- [x] the headless composable is updated accordingly
- [x] note: fix todo in `packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.ct.tsx`
       -> maybe always setting the checkbox to "disabled" might help...
       -> Postponed to #1026 
- [x] write test for `packages/sit-onyx/src/composables/selectAll.ts`

#### Out of scope
- [Keyboard Features missing in the single-select so far](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#keyboardinteraction) -> #996 

### Definition of Done

- [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/story/support-listbox--multiselect)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

### Implementation details

- [x] Select all: use the existing translation as default label
- [x] align API (props etc.) with the OnyxCheckboxGroup
- [x] - The modelValue prop and update:modelValue should be generically typed based on whether its multiselect or single select

#### Applicable ARIA Pattern

[Listbox pattern](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)

**Comment by mj-hof** [comment]
Please refine ACs in more detail (in & out of scope, e.g. grouping)

**Comment by BoppLi** [comment]
@jannick-ux I have a question about the select all. if it is indeterminate, is it considered "selected" in terms of the color highligthing when hovering? so should the text be blue or default?
current implementation:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/522c3276-a967-4f79-bbf7-f15f69b94ebb)

only if all are selected it gets blue:
![Image](https://github.com/SchwarzIT/onyx/assets/151019977/beae3340-b5fb-4fb5-b751-2df0e03ac7ad)

**Comment by jannick-ux** [comment]
The select all does not use color for the background in general. So please remove it. The check all only indicates by the checkbox itself, that it is checked or unchecked. BG is always default just like the text.
