### ISSUE TITLE
Implement design token update for docs

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#736]
### Why?

Since we also have tokens with a very long value, we want to update the design for all design tokens as shown below.

### Design

[Figma link](https://www.figma.com/file/EBi98T51T9fGfjrYYfsulg/onyx---Archive?type=design&node-id=3337-4232&mode=dev)

![Image](https://github.com/SchwarzIT/onyx/assets/67898185/dea68fb0-17d4-4d4a-92a0-fd5d2d3946c7)

### Acceptance criteria

- the design is updated for:
  - [x] spacings
  - [x] border radius
  - [x] shadows

#### Out of scope:

- colors

### Definition of Done

- covered by tests
  - [x] visual tests (Playwright screenshots)
- [x] updated version + documentation is deployed

**Approval**

- [Deployed Docs](https://onyx.schwarz/variables/shadows.html)
- [x] approved by designer @jannick-ux
- [x] approved by dev @JoCa96

**Comment by mj-hof** [comment]
@jannick-ux will deliver the mobile behaviour
