### ISSUE TITLE
Implement listbox loading and empty

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#743]
### Depends on

- #564
- #744

### Why?

The listbox should support a loading state to indicate that the options are loading.

### Design

[Figma link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1253-59736&mode=dev).

### Acceptance criteria

- [x] a dots loading indicator can be displayed
- [x] a "Load more" button can be displayed
- [x] an empty state can be shown
- [ ] ~~headless composable is updated accordingly~~

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Lazy loading example](https://storybook.onyx.schwarz/?path=/story/support-onyxlistbox--lazy-loading)
- [Button loading example](https://storybook.onyx.schwarz/?path=/story/support-onyxlistbox--button-loading)
- [Empty example](https://storybook.onyx.schwarz/?path=/story/support-onyxlistbox--empty)
- [x] approved by designer @jannick-ux
- [x] approved by dev @BoppLi 

### Implementation details

- add a default translation for the "Load more" and empty text

### Aria pattern

https://www.w3.org/WAI/ARIA/apg/patterns/listbox/

If the complete set of available options is not present in the DOM due to dynamic loading as the user scrolls, their [aria-setsize](https://w3c.github.io/aria/#aria-setsize) and [aria-posinset](https://w3c.github.io/aria/#aria-posinset) attributes are set appropriately.

**Comment by larsrickert** [comment]
Regarding the aria pattern: If the complete set of available options is not present in the DOM due to dynamic loading as the user scrolls, their [aria-setsize](https://w3c.github.io/aria/#aria-setsize) and [aria-posinset](https://w3c.github.io/aria/#aria-posinset) attributes are set appropriately.

**Comment by larsrickert** [comment]
Note on the aria pattern: The `aria-setsize` and `aria-posinset` are only needed if only a subset of available options is rendered in the DOM, e.g. there are 100 options but only 25 are rendered until the user scrolls to the end.

This is not needed for the loading because all options that exist are also rendered in the DOM. We don't have virtual scrolling

**Comment by JoCa96** [comment]
> Note on the aria pattern: The `aria-setsize` and `aria-posinset` are only needed if only a subset of available options is rendered in the DOM, e.g. there are 100 options but only 25 are rendered until the user scrolls to the end.
> 
> This is not needed for the loading because all options that exist are also rendered in the DOM. We don't have virtual scrolling

That is not correct per my reading of the spec:

> Not required if all elements in the set are present in the DOM.

The set is **all** options, but we only show a subset.

> To orient the user by saying an element is "item X out of Y," the [assistive technologies](https://w3c.github.io/aria/#dfn-assistive-technologies) would use X equal to the [aria-posinset](https://w3c.github.io/aria/#aria-posinset) [attribute](https://dom.spec.whatwg.org/#concept-attribute) and Y equal to the aria-setsize attribute.
> If all items up to the current item in a set are present in the document structure, it is not necessary to set this [attribute](https://dom.spec.whatwg.org/#concept-attribute), as the [user agent](https://infra.spec.whatwg.org/#user-agent) can automatically calculate the position for these items. However, if all previous items in the set are not present in the document structure at a given moment, the author MUST set this [attribute](https://dom.spec.whatwg.org/#concept-attribute) to provide an explicit indication of an element's position.

Unfortunately, this section is written in a way that can be misunderstood. But by the context and the last sentence, it seems to me that `If all items up to the current item [...], it is not necessary  to set this attribute` refers to `aria-posinset`. 

So while `aria-posinset` is not necessary for us, `aria-setsize` is necessary. Which makes sense, because Y in `item X out of Y` would be changed by scrolling.

**Comment by larsrickert** [comment]
> So while `aria-posinset` is not necessary for us, `aria-setsize` is necessary. Which makes sense, because Y in `item X out of Y` would be changed by scrolling.

We can not know the setsize. Example: You have pagination and load 50 options from the backend (lets say the database has 1000 options). The setsize would be 1000 but we can not know this because we only have 50 and render all of them.

As I understood, `setsize` is about pagination, not about regular lists

**Comment by JoCa96** [comment]
But the user knows the size and can set it.

Also:
> If the total number of items is unknown, authors SHOULD set the value of aria-setsize to -1.

**Comment by larsrickert** [comment]
> But the user knows the size and can set it.

I am thinking about the implementation...we can not make it required because there can be no loading but if its optional I can imagine not no-one is using it

**Comment by JoCa96** [comment]
- [ ] If possible, the `useScrollEnd` composable should be implemented using the [IntersectionOberserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) and instead of `scrollOffset` use something like `OptionOffsetTrigger`, which defines how many options are minimum can be scrolled before lazy loading is triggered
- [ ] `aria-setsize` is required for lazy-loading, as otherwise the wrong list size will be communicated to the screen-reader:

![Image](https://github.com/SchwarzIT/onyx/assets/18483883/10e8e949-c4f4-4dd0-96b8-55ede39898ff)
![Image](https://github.com/SchwarzIT/onyx/assets/18483883/ed6bb852-6e11-4fb3-86c2-5399d589122e)

**Comment by larsrickert** [comment]
> * [ ]  If possible, the `useScrollEnd` composable should be implemented using the [IntersectionOberserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) and instead of `scrollOffset` use something like `OptionOffsetTrigger`, which defines how many options are minimum can be scrolled before lazy loading is triggered
> * [ ]  `aria-setsize` is required for lazy-loading, as otherwise the wrong list size will be communicated to the screen-reader:

I created a follow up ticket for this: #931
