### ISSUE TITLE
Implement OnyxForm component

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#757]
### Definition of Done

- The following component requirements are implemented:
  - [ ] `skeleton`
  - [ ] `density`
  - [ ] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [ ] covered by component tests
- [ ] screenshot tests are updated
- [ ] follow-up tickets were created if necessary
- [ ] updated version + documentation is deployed
- [ ] Storybook can show the feature
- [ ] Storybook code snippet of new/changed examples are checked that they are generated correctly
- [ ] Set task to `In Approval`

**Approval**

- Storybook 
- Deployed Docs 
- [ ] approved by designer @jannick-ux
- [ ] approved by dev

**Comment by BoppLi** [comment]
From Retro: 

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/a7cb6606-4233-4b54-b54e-92a6238c9e2b)

**Comment by BoppLi** [comment]
brainstorming: modes for showing validation errors / validation on user side
- initial
- onInput/onChange
- onBlur
- onSubmit
