### ISSUE TITLE
Fix Playwright inconsistency of hover/focus icon colors

### ISSUE THREAD

**Issue by BoppLi** [SchwarzIT/onyx#770]
Problem: In the playwright screenshots, the icon color of the OnyxSelect does not react on hover/focus.

## How it looks in playwright:

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/966d27f8-310e-4312-be07-cc48c3f6843b)

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/39ade7dd-9e59-4585-9fcc-a3f2b1822bed)

## How it looks in Storybook:

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/8f52d94d-7da5-40d5-88b7-5a9f373924f9)

![Image](https://github.com/SchwarzIT/onyx/assets/151019977/93d89781-1c9b-4c00-a0a9-ca54540a1782)

**Comment by larsrickert** [comment]
The issue has been fixed in the meantime / its no longer reproducable
