### ISSUE TITLE
Adjust OnyxBadge to align with other components

### ISSUE THREAD

**Issue by JoCa96** [SchwarzIT/onyx#829]
We want to align the property naming between the designs and the implementation.

- [ ] Rename "type" in Figma to "variant"

https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1113%3A2754&mode=dev

![Image](https://github.com/SchwarzIT/onyx/assets/18483883/7ae542e8-1a08-4dcd-854a-c82be44f48c1)

**Comment by larsrickert** [comment]
Proposal: Rename properties of all components that change the color to `color` instead of `type` or `variant` since its more intuitive for the user in my opinion
