### ISSUE TITLE
Define setup tooling for web-api-support checks (CanIUse)

### ISSUE THREAD

**Issue by larsrickert** [SchwarzIT/onyx#83]
### Why?

Check if we can e.g. setup eslint (or a similar tool) to check/warn for Web API support / browser compatibility in our code.
So that we are notified when we try to use a Web API that is not supported by X percent of browsers.

Also look into the necessity of polyfills etc for supporting older browsers in the company

### Acceptance criteria

- [x] Pipeline should check browser support of the web APIs we use
- [x] Define a list of relevant browser
- [x] If there are issues that get out of scope, create tickets
- [x] Update the Docs to reflect which browsers + versions are supported (ideally it is connected to a browserlists file)

### Definition of Done

- [x] follow-up tickets were created if necessary
    - #1970 
    - #1997 
- [x] updated version + documentation is deployed

**Approval**

- [Documentation link](https://onyx.schwarz/development/#browser-support)
- [x] approved by ux @mj-hof 
- [x] approved by dev @JoCa96 

### Implementation details

- Info: ask A.S. from the department "Workplace Platform Design" about which relevant browsers & versions we have to support

**Comment by oemueller** [comment]
Proposed browserlist: https://browsersl.ist/#q=%3E+0.5%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead

**Comment by oemueller** [comment]
with `npx browserslist` we can get a list of supported browsers -> based on that we can render a table of all supported browsers in the Docs

**Comment by oemueller** [comment]
Desktop browser requirements: Edge, Safari (last 2 Versions), Firefox ESR (Source: Workplace Platform Design)
