### ISSUE TITLE
Implement simple navigation bar

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#867]
### Open Questions/To-dos

- [x] Decide if the separator should be just a class or a separate component? Seperator for user menu on the right is a slot component
- [x] Do we include mobile behavior in this ticket? No, not part of that ticket

### Why?

This component is crucial for our library

### Design

[Figma Link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1709%3A12388&mode=dev)

### Acceptance criteria

- [x] Appname area supports both icon and text (optional)
- [x] A slot for icon or custom svg image is available
- [x] Appname area is clickable
- [x] Show back button prop
- [x] It should follow the grid

#### Out of scope

- mobile/responsive behaviour, #1073

### Definition of Done

- [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [ ] Set task to `In Approval`

### Implementation Details

- [x] The app Name respects line breaks
- [x] We don't restrict max-width by default

**Approval**

- [Storybook](https://storybook.onyx.schwarz/?path=/docs/components-navbar--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @MajaZarkova 

#### Reference implementations

[CoreUI Reference Link](https://core-ui.schwarz/components/scu-top-bar)

#### Applicable ARIA Pattern

[Disclosure navigation](https://www.w3.org/WAI/ARIA/apg/patterns/disclosure/examples/disclosure-navigation/)

**Comment by jannick-ux** [comment]
This is now with center alignment. Is left alignment available as well? With this component there is a high dependency on the overall page grid. Left aligned should be the fault here. 
Or will it be part of another ticket?

**Comment by larsrickert** [comment]
> This is now with center alignment. Is left alignment available as well? With this component there is a high dependency on the overall page grid. Left aligned should be the fault here. Or will it be part of another ticket?

Currently the default is left aligned but it also adjust to the grid so if you set the grid to be max md and centered, the nav bar will also adjust accordingly

**Comment by jannick-ux** [comment]
Ah okay, becaus with the examples I saw, there was a unused white gap on the left, that looked like it would exist because of center alignment

**Comment by larsrickert** [comment]
@jannick-ux  As discussed the padding is correct but I fixed the grid implementation to align with the nav bar.
You can check the screenshots here:
- [default](https://github.com/SchwarzIT/onyx/blob/main/packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/grid-default-chromium-linux.png)
- [max width](https://github.com/SchwarzIT/onyx/blob/main/packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/grid-max-width-chromium-linux.png)
- [max width centered](https://github.com/SchwarzIT/onyx/blob/main/packages/sit-onyx/playwright/snapshots/components/OnyxNavBar/grid-max-center-chromium-linux.png)
