### ISSUE TITLE
Implement OnyxNavItem

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#874]
### Open Questions/To-dos

- [x] When we implemented the OnyxBadge we set the dot as out of scope. We don't have a decision whether the dot should be a separate component or part of OnyxBadge. The dot should be used inside OnyxNavItem, do we set it as out of scope here as well?

Implement the dot as a slot, so the user have a possibility to use a dot or a badge

Relates to #841 

### Why?
This component is needed and will be used inside the navigationBar. This is just a support component

### Design

[Figma Link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1707%3A7991&mode=dev)

### Acceptance criteria

- [x] Supports additional badge alongside the text
- [x] Supports two modes:
  - [x] Opens the linked page **on click**
  - [x] Opens a flyout with multiple pages **on hover**

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] follow-up tickets were created if necessary
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- Storybook [Storybook](https://storybook.onyx.schwarz/?path=/docs/components-navitem--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @larsrickert 

#### Out of scope

- Use grouped listbox for the MoreFlyout when the navItems are combined into one (while resizing) -> #986 
- Make sure that we don't lose the dot/badge from the navItem when it's combined into moreFlyout -> #742 
- onyx doesn't automatically open any links, follow up ticket -> #447 

#### Reference implementations

- Suggestion to use the OnyxListbox as the flyout mentioned before
- [CoreUI Reference](https://core-ui.schwarz/components/scu-top-bar-nav-item)

#### Applicable ARIA Pattern

[ARIA Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/)

**Comment by MajaZarkova** [comment]
Notes for Monday daily

- [ ] Is onyx marking the parent active when a child is active?
- [ ] Can parent be also clicklable if it has children?
- [ ] Can a navItem be disabled?
- [ ] If all the children are disabled is the parent disabled?
- [ ] Do we have special treatment for external links, eg. arrow icon (future questions)

**Comment by MajaZarkova** [comment]
#447

**Comment by jannick-ux** [comment]
Before approving: please check thehover state of the selected flyout-item. Currently it has the same optics like a non-selected-item. But it should look different.
https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1124-18839&mode=design&t=VeOiYlOSoYy7HVE5-4

The goal looks like this: same background color like the non-hovered selected item but with primary colored text.

**Comment by larsrickert** [comment]
@MajaZarkova Ideally when pressing tab, it should directly focus the listbox instead if having to press tab two times.
I need the same behavior for my user fly out and I think @JoCa96 already implemented this in his combox PR

**Comment by MajaZarkova** [comment]
@larsrickert , good point. I'll implement it.
@jannick-ux , thank you for finding the bug.

I'll create a PR fixing both issues :)

**Comment by larsrickert** [comment]
@MajaZarkova Currently the options are always visible / taking up height which does not work as intended when used inside the nav bar because the whole nav bar adjusts its height then.

We propably should position it absolute to the parent

![Image](https://github.com/SchwarzIT/onyx/assets/67898185/70303d87-6712-4801-b39e-19b6de8742a1)

**Comment by MajaZarkova** [comment]
@larsrickert , follow up bug ticket is created -> #1043

**Comment by jannick-ux** [comment]
Please have a look on the text styles of the component in default and in active state.
Default state uses "paragraph-default", active state uses "h3". So in the end, when the item is active, the font gets more weight. Rest looks nice to me
