### ISSUE TITLE
Implement OnyxTimer

### ISSUE THREAD

**Issue by MajaZarkova** [SchwarzIT/onyx#882]
### Why?

This component is needed and will be used inside the navigationBar. This is just a support component.

### Design

[Figma Link (Inside the Context Area section)](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?node-id=1709%3A12336&mode=dev)

### Acceptance criteria

- [x] can show a label
- [x] Has property endTime
- [x] Emits an event when the time is up

### Definition of Done

- [x] covered by component tests
- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Storybook link](https://storybook.onyx.schwarz/?path=/docs/support-timer--docs)
- [Example inside nav bar](https://storybook.onyx.schwarz/?path=/story/components-navbar--with-logout-timer)
- [x] approved by designer @jannick-ux
- [x] approved by dev @MajaZarkova 

### Implementation details

- we should use `clearTimeout` if the timeout changes so we don't have trailing timers
- create a composable for handling timers
- ⚠️ the implementation must not block the page from going to sleep: https://developer.chrome.com/docs/web-platform/page-lifecycle-api

#### Reference implementations

Make use of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time
[CoreUI Reference](https://core-ui.schwarz/components/scu-timer)

**Comment by oemueller** [comment]
Hi @jannick-ux - shall we also display hours and days on top of minutes and seconds ? 
what about months ? In Figma I only see minutes and seconds 🙂

**Comment by jannick-ux** [comment]
Hi @oemueller  
Yes timer should be customizable by the project developer. However there needs to be a limit on what should be supported. Days, month and years can be ignored for now. This is not our focus at the moment.
 But hours, minutes and seconds should be possible in general. Pending on the projects need, all combinations of it should be possible to use (e.g. "only seconds", "minutes + seconds", "hours + minutes"). The default by onyx should be "minutes + seconds".

Thanks for your work :D
