### ISSUE TITLE
Concept textarea

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#90]
### Create textarea
- [ ] all needed variation
- [ ] all necessary states
- [ ] dark mode
- [ ] keyboard support
- [ ] density

### Functions
- [ ] Can be used in Figma and is available as a component
- [ ] Shows all states

### Figma
- [ ] dev handover
- [ ] ux component

### documentation
- [ ] keyboard support
- [ ] property description
- [ ] textual documentation
- [ ] component grouping

**Comment by jannick-ux** [comment]
@mj-hof for the first concept, a basic variation is enough, I guess? 
Additional functionality like fileupload, quotes, inputadjustemnts (like the github comment box) are not the scope for now, from my pov.
