### ISSUE TITLE
Implement icon from figma downloading cli tool

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#939]
### Discussed in https://github.com/SchwarzIT/onyx/discussions/184

<div type='discussions-op-text'>

<sup>Originally posted by **JoCa96** January 23, 2024</sup>
Currently the designers need to maintain the Icons in two places: Figma & and our internal Schwarz Icon Repo. 
We should evaluate if its possible to use Figma as a Single-Source-of-Truth.</div>

### Why

Currently the designers need to maintain the Icons in two places: Figma & and our internal Schwarz Icon Repo. 
We should evaluate if its possible to use Figma as a Single-Source-of-Truth. The [Icon Library - UX Schwarz IT](https://www.figma.com/design/ZtlUPkO9ATUCV42Wkg7P0o/Icon-Library---UX-Schwarz-IT?node-id=3270-179&m=dev) Figma file should we used for the icon source and for the `@sit-onyx/icons` npm package, the icons should be imported automatically (on a schedule, e.g. daily) from this Figma file and released.

### Acceptance criteria
- [x] Download icon SVGs from Figma
- [x] Get meta data (category, icon name, alias names)
- [x] Optimise downloaded icons
- [x] If changes exists: Publish new version of `@sit-onyx/icons` with changeset + changelog
- [x] check when to run the pipeline regularly (e.g. daily, weekly etc.)
- [x] Implement generically (only download + meta data), so it can be used also for other icon libraries (e.g. pass Figma file as parameter etc.). Maybe similar or as enhancement of our Figma CLI utility?
- [x] is an onyx independent solution
- [x] [Icon docs](https://onyx.schwarz/icons.html) supports search by alias names 

#### Follow up tickets

- #1802
- #1803

**Approval**

- [Icon docs](https://onyx.schwarz/icons.html)
- [Figma CLI docs](https://onyx.schwarz/development/packages/figma-utils.html#import-icons)
- [x] approved by designer @jannick-ux
- [x] approved by dev @MajaZarkova 

### Implementation Details
[Figma REST API](https://www.figma.com/developers/api#get-file-nodes-endpoint)

**Comment by larsrickert** [comment]
@MajaZarkova For review: #1813
