### ISSUE TITLE
Implement OnyxAvatar

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#947]
### Design

[Figma link](https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=1625-42061&mode=design&t=Rzafyz5FqsKcLCO0-4)

### Acceptance criteria

- [x] a male avatar can be shown
- [x] a female avatar can be shown
- [x] a diverse avatar can be shown
- [x] an avatar stack can be shown
- [x] a custom image can be shown

### Definition of Done

- The following component requirements are implemented:
  - [x] example usage added to `apps/alpha-test-app/src/views/HomeView.vue`
- [x] covered by component tests
- [x] screenshot tests are updated
- [x] updated version + documentation is deployed
- [x] Storybook can show the feature
- [x] Set task to `In Approval`

**Approval**

- [Avatar](https://storybook.onyx.schwarz/?path=/docs/components-avatar--docs)
- [Avatar stack](https://storybook.onyx.schwarz/?path=/docs/components-avatarstack--docs)
- [x] approved by designer @jannick-ux
- [x] approved by dev @MajaZarkova 

### Implementation details

- for the male/female version, if possible use a SVG and set the colors via CSS variables so they adapt to light/dark mode and different color themes

**Comment by larsrickert** [comment]
Open UX points / Figma changes:
- rename "diverse" to "initials"
- add size 96px (and check if font size for this size is correct)
- check colors in dark mode
- add row gap for stack if wrapped to multiple lines?
- stack: support setting a max count to show a "+4" indicator?

**Comment by jannick-ux** [comment]
before approval: can the avatar stack also be used in the same size variations like the avatar component?
Is there the possibility for a max number visualized by "+4" for example?
I cannot find it in storybook.

**Comment by larsrickert** [comment]
@jannick-ux I added it :) https://storybook.onyx.schwarz/?path=/story/components-avatarstack--limited-count
