### ISSUE TITLE
Define Code Connect feature in Figma

### ISSUE THREAD

**Issue by mj-hof** [SchwarzIT/onyx#984]
Check if the new Code Connect feature in Figma is a neccessary improvement to:
- Design systems
- DEV Experience
- Worth the time invest

Tutorial Video of Figma Framework Conference:  
- https://youtu.be/5GVNfbltrQg?si=2OUx2TsjjrDL1MEl 
- https://youtu.be/FrgH2VMIOf8
- https://youtu.be/5GVNfbltrQg?feature=shared
- https://youtu.be/FrgH2VMIOf8?feature=shared

**Comment by larsrickert** [comment]
I will close this issue since the Figma code connect feature does not work with Vue, see [supported frameworks](https://github.com/figma/code-connect?tab=readme-ov-file#setup)
